hyperledger-caliper/caliper

benchmark/simple/fabric.json, src/fabric/create-channel.js
=> reject create-channel if no channel information found

benchmark/drm/config.json, benchmark/simple/config-fabric.json, benchmark/simple/config-iroha.json
=> remove obsolete txNumbandTps from config files

CONTRIBUTING.md
=> Initiate CONTRIBUTING doc

README.md, network/fabric/simplenetwork/docker-compose.yaml, src/fabric/e2eUtils.js, src/fabric/instantiate-chaincode.js
Minor change after testing with fabric v1.1.0:
1. force pure GO resolver for fabric/simplenetwork
2. fix wrong prompts
=> update with fabric v1.1.0

docs/Composer.md
Closes #25 
Changes include:
- Update the named directory to match the required folder structure.
- Provides more guidance in creating the required test files
Signed-off-by: Nick Lincoln <nkl199@yahoo.co.uk>
=> update composer docs for creating own tests

benchmark/composer/composer-samples/basic-sample-network.js, src/contract/composer/basic-sample-network/README.md, src/contract/composer/basic-sample-network/lib/sample.js, src/contract/composer/basic-sample-network/models/sample.cto, src/contract/composer/basic-sample-network/permissions.acl
Signed-off-by: Nick Lincoln <nkl199@yahoo.co.uk>
closes #44 
PR includes:
- updates to all test resources (contract resources and test runner script) to ensure consistency in model namespace used.
=> ensure consistent namespace in sample

.eslintignore, docs/Architecture.md, src/comm/bench-flow.js, src/comm/blockchain-interface.js, src/comm/blockchain.js, src/comm/client/client-util.js, src/comm/client/client.js, src/comm/client/local-client.js, src/comm/client/zoo-client.js, src/comm/client/zoo-util.js, src/comm/monitor-docker.js, src/comm/monitor-interface.js, src/comm/monitor-process.js, src/comm/monitor.js, src/comm/report.js, src/comm/util.js
This PR is related to issue #48 
1. Update files of benchmark engine, client, monitor, report, etc. to follow the eslint rules
2. Update log to accept unspecified number of arguments
=> Eslint compatible

.eslintignore, src/fabric/constant.js, src/fabric/create-channel.js, src/fabric/e2eUtils.js, src/fabric/fabric.js, src/fabric/install-chaincode.js, src/fabric/instantiate-chaincode.js, src/fabric/join-channel.js, src/fabric/util.js
Part of the solution for #48 
The Fabric subfolder is now lint-error/warning free.
=> Fix Fabric-related lint errors and warnings.

benchmark/smallbank/config-smallbank-sawtooth.json, benchmark/smallbank/main.js, benchmark/smallbank/protos/smallbank.proto, benchmark/smallbank/query.js, benchmark/smallbank/smallbankOperations.js, network/sawtooth/smallbank/sawtooth-smallbank-go.yaml, package.json, src/sawtooth/Application/BatchBuilderFactory.js, src/sawtooth/Application/SmallBankBatchBuilder.js
Adding smallbank benchmark use case which simulates bank operations
Signed-off-by: Ramakrishna Srinivasamurthy <ramakrishna.srinivasamurthy@intel.com>
=> Adding smallbank benchmark use case which simulates bank operations

README.md
Signed-off-by: Ramakrishna Srinivasamurthy <ramakrishna.srinivasamurthy@intel.com>
=> Updated the sawtooth version in Readme doc file

.eslintignore, .gitignore, benchmark/smallbank/config-smallbank-sawtooth.json, package.json, src/comm/blockchain-interface.js, src/comm/blockchain.js, src/comm/client/local-client.js, src/fabric/e2eUtils.js, src/fabric/fabric.js, src/iroha/iroha.js, src/sawtooth/Application/BatchBuilder.js, src/sawtooth/Application/SimpleBatchBuilder.js, src/sawtooth/sawtooth.js
1. Update blockchain interfaces and txns count calculation to support batch
2. Update sawtooth code to follow linting rules
=> Support batch in framework

src/gui/src/demo.js
This change modified the demo.js to save report's path after testing
=> save report's after test

benchmark/smallbank/smallbankOperations.js
=> Fix amalgamate payload

src/sawtooth/Application/SimpleBatchBuilder.js
Support batch for the simple benchmark and fix the args bug.
=> Support batch for the simple benchmark

docs/Fabric Configuration.md
This patch fixes a typo in the document.
=> Fix typo in Document

network/fabric/simplenetwork/configtx.yaml
To make it work with the latest fabric code, while still being
compatible with v1.0/1.1
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Change the profile section in fabric configtx.yaml file

src/gui/src/demo.js
close #120 
This PR limits the length of x-axis to prevent oversized log files.
modify max x-axis length
=> fix issue#120: limit size of tmp demo log

benchmark/smallbank/config-smallbank-sawtooth.json, benchmark/smallbank/sawtooth.json
Config file path is corrected
Signed-off-by: Ramakrishna Srinivasamurthy <ramakrishna.srinivasamurthy@intel.com>
=> Config file path is corrected

network/sawtooth/simplenetwork/Dockerfile, src/contract/sawtooth/simple/simple_python/packaging/systemd/sawtooth-simple-tp-python.service, src/contract/sawtooth/simple/simple_python/sawtooth_simple/processor/handler.py, src/contract/sawtooth/simple/simple_python/sawtooth_simple/processor/main.py
Signed-off-by: Justin Kenney <justin.kenney@emc.com>
=> Updated Sawtooth Simple Example to Work

benchmark/composer/composer-micro/query-asset.js, benchmark/composer/composer-samples/basic-sample-network.js, benchmark/composer/composer-samples/bond-network.js, benchmark/composer/composer-samples/digitalproperty-network.js, benchmark/composer/composer-samples/marbles-network.js, benchmark/composer/composer-samples/perishable-network.js, benchmark/composer/composer-samples/vehicle-lifecycle-network.js, benchmark/drm/publish.js, benchmark/drm/query.js, benchmark/marbles/init.js, benchmark/marbles/query.js, benchmark/simple/open.js, benchmark/simple/query.js, benchmark/smallbank/query.js, benchmark/smallbank/smallbankOperations.js, src/comm/client/local-client.js
fixes #146 
Signed-off-by: jiangyaoguo <jiangyaoguo@gmail.com>
=> Fix benchmark drm

README.md
=> Add empty line

src/comm/client/client-util.js
=> Fix issue #39

benchmark/simple/config-sawtooth.json, benchmark/simple/open.js, benchmark/simple/query.js
Signed-off-by: Nidhi Kumari <nidhisolanki44@gmail.com>
=> Changed simple benchmark to have multiple transactions in a batch

benchmark/simple/open.js, src/comm/client/client-util.js
=> Set txnPerBatch default value

src/comm/blockchain-interface.js, src/comm/blockchain.js, src/fabric/e2eUtils.js, src/fabric/fabric.js, src/iroha/iroha.js
In some cases it might be useful to query the ledger by function different from the 'query'.
=> add the possibility to specify query function name

benchmark/composer/config-composer.json, src/comm/rate-control/pidRate.js, test/comm/rate-control/pidRate.js
Required fix for PID rate controller as part of #142 
-> change to use the current backlog directly
-> update unit tests to reflect change
-> add PID to the composer 'standard' test set config
=> fix PID rate controller for new client test mechanism

src/sawtooth/sawtooth.js
=> Fix typo and eslint error

README.md
=> Clarified Fabric SDK install instructions in docs

src/comm/monitor.js
=> Fix length undefined

benchmark/simple/sawtooth.json, benchmark/smallbank/sawtooth.json, src/sawtooth/sawtooth.js
Signed-off-by: Ramakrishna Srinivasamurthy ramakrishna.srinivasamurthy@intel.com
=> Changed the sawtooth adapter to take multiple rest end points

benchmark/simple/sawtooth.json, benchmark/smallbank/sawtooth.json, package.json, src/gui/www/index.html, src/sawtooth/Application/BatchBuilderFactory.js, src/sawtooth/sawtooth.js, test/sawtooth/Application/BatchBuilderFactory.js
https://github.com/hyperledger/caliper/issues/189
=> Moved the batch builder factory configuration into the sawtooth.json configuration files

src/sawtooth/sawtooth.js
=> Fix sawtooth test not exit normally

.gitignore, package.json, src/comm/bench-flow.js, src/fabric/create-channel.js, src/fabric/install-chaincode.js, src/fabric/instantiate-chaincode.js, src/fabric/join-channel.js
=> Removed tape-related code

benchmark/composer/main.js, benchmark/drm/main.js, benchmark/marbles/main.js, benchmark/simple/main.js, benchmark/smallbank/main.js, src/comm/bench-flow.js, src/comm/blockchain-interface.js, src/comm/blockchain.js, src/comm/client/client-util.js, src/comm/client/client.js, src/comm/client/local-client.js, src/fabric/create-channel.js, src/fabric/e2eUtils.js, src/fabric/fabric.js, src/fabric/install-chaincode.js, src/fabric/instantiate-chaincode.js, src/fabric/join-channel.js, src/fabric/util.js
Refactored the `Promise` chains to the `async/await` pattern in the following components:
* Core benchmark code
* General blockchain classes
* Client classes (except for ZooKeeper-related code)
* Fabric adapter
* `main.js` files of the sample benchmarks
#192
=> Refactored Promise chains in core/client/blockchain/Fabric parts

.travis/script.sh, package.json
Part1 for #229 
- addition of npm scripts to package file
- modification of travis build file to use the npm script to configure for baseline test runs in build
Pending addition(s):
- website doc guide changes to indicate the presence/use of the scripts
=> add config scripts to setup target test platform

docs/RateControllers.md
=> Add fixed feedback rate doc

src/fabric/e2eUtils.js
Check whether a chaincode has been installed and instantiated, if it has, not throw an error, to enable repeated tests.
1.
2.
3.
4.
=> Check whether a chaincode has been installed and instantiated

src/comm/blockchain-interface.js, src/comm/blockchain.js, src/comm/client/client-util.js, src/comm/client/local-client.js, src/comm/rate-control/rateInterface.js, src/fabric/e2eUtils.js, src/fabric/fabric.js
=> Assign target peers based on client index

docs/Fabric_Configuration.md
Aligned the documentation according to PR #260 
Preview at: https://aklenik.github.io/caliper/docs/Fabric_Configuration.html
=> Modify install instructions for Fabric dependencies

docs/Writing_Adapters.md
resolve the pr #283 format mistakes
=> Fix page format's mistakes

.eslintignore, src/adapters/fabric/ChannelSignedTransaction.js, src/adapters/fabric/create-channel.js, src/adapters/fabric/e2eUtils.js, src/adapters/fabric/fabric.js
Resolve PR #279  bugs, including querying chaincode bug， creating channel bug and file mode bug.
=> Fix query chaincode ，create channel and file mode bugs

benchmark/simple/main.js, network/fabric-v1.1/customdomain/docker-compose.yaml, src/adapters/fabric/create-channel.js, src/adapters/fabric/e2eUtils.js
=> Provie debug info for channel

src/comm/util.js
Signed-off-by: TaoChen <clumsky@163.com>
=> Provide error information

docs/Caliper_FAQ.md
=> add caliper FAQ

network/fabric-v1.1/customdomain/docker-compose-tls.yaml, network/fabric-v1.1/customdomain/docker-compose.yaml, network/fabric-v1.1/customdomain/fabric-go-tls.json, network/fabric-v1.1/customdomain/fabric-go.json, network/fabric-v1.1/customdomain/fabric-node-tls.json, network/fabric-v1.1/customdomain/fabric-node.json, network/fabric-v1.2/customdomain/docker-compose-tls.yaml, network/fabric-v1.2/customdomain/docker-compose.yaml, network/fabric-v1.2/customdomain/fabric-go-tls.json, network/fabric-v1.2/customdomain/fabric-go.json, network/fabric-v1.2/customdomain/fabric-node-tls.json, network/fabric-v1.2/customdomain/fabric-node.json, network/fabric-v1.4/customdomain/fabric-go.json
=> Fix fabric1.4 customdomain CA name errors

docs/1_Getting_Started.md, docs/Fabric_Ccp_Configuration.md
Documentation for the new Fabric CCP adapter #296 
Preview: https://aklenik.github.io/caliper/docs/Fabric_Ccp_Configuration.html
=> Documentation for the Fabric CCP adapter

network/fabric-v1.0/customdomain/docker-compose-tls.yaml, network/fabric-v1.0/customdomain/docker-compose.yaml, network/fabric-v1.0/customdomain/fabric-ccp-go-tls.yaml, network/fabric-v1.0/customdomain/fabric-ccp-go.yaml, network/fabric-v1.0/customdomain/fabric-go-tls.json, network/fabric-v1.0/customdomain/fabric-go.json, network/fabric-v1.1/customdomain/fabric-ccp-go-tls.yaml, network/fabric-v1.1/customdomain/fabric-ccp-go.yaml, network/fabric-v1.1/customdomain/fabric-ccp-node-tls.yaml, network/fabric-v1.1/customdomain/fabric-ccp-node.yaml, network/fabric-v1.2/customdomain/fabric-ccp-go-tls.yaml, network/fabric-v1.2/customdomain/fabric-ccp-go.yaml, network/fabric-v1.2/customdomain/fabric-ccp-node-tls.yaml, network/fabric-v1.2/customdomain/fabric-ccp-node.yaml
Change CA names of the customdomain networks for the fabric-ccp adapter
=> change CA names for customdomain

docs/1_Getting_Started.md, docs/Burrow_Configuration.md
Signed-off-by: Gregory Hill <greg.hill@monax.io>
=> update docs with bench cmd

network/fabric-v1.1/3org1peercouchdb/fabric-ccp-go-mutual-tls.yaml, network/fabric-v1.1/3org1peercouchdb/fabric-ccp-go-tls.yaml, network/fabric-v1.1/3org1peercouchdb/fabric-ccp-node-mutual-tls.yaml, network/fabric-v1.1/3org1peercouchdb/fabric-ccp-node-tls.yaml, network/fabric-v1.1/3org2peergoleveldb/fabric-ccp-go-mutual-tls.yaml, network/fabric-v1.1/3org2peergoleveldb/fabric-ccp-go-tls.yaml, network/fabric-v1.1/3org2peergoleveldb/fabric-ccp-node-mutual-tls.yaml, network/fabric-v1.1/3org2peergoleveldb/fabric-ccp-node-tls.yaml, network/fabric-v1.1/dev/fabric-ccp-go-mutual-tls.yaml, network/fabric-v1.1/dev/fabric-ccp-go-tls.yaml, network/fabric-v1.1/dev/fabric-ccp-node-tls.yaml, network/fabric-v1.2/3org1peercouchdb/fabric-ccp-go-mutual-tls.yaml, network/fabric-v1.2/3org1peercouchdb/fabric-ccp-go-tls.yaml, network/fabric-v1.2/3org1peercouchdb/fabric-ccp-node-mutual-tls.yaml, network/fabric-v1.2/3org1peercouchdb/fabric-ccp-node-tls.yaml, network/fabric-v1.2/3org2peergoleveldb/fabric-ccp-go-mutual-tls.yaml, network/fabric-v1.2/3org2peergoleveldb/fabric-ccp-go-tls.yaml, network/fabric-v1.2/3org2peergoleveldb/fabric-ccp-node-mutual-tls.yaml, network/fabric-v1.2/3org2peergoleveldb/fabric-ccp-node-tls.yaml, network/fabric-v1.2/dev/fabric-ccp-go-mutual-tls.yaml, network/fabric-v1.2/dev/fabric-ccp-go-tls.yaml, network/fabric-v1.2/dev/fabric-ccp-node-tls.yaml, package.json, src/adapters/fabric-ccp/fabric.js
Resolves issues #344 and #345 (since both relate to Fabric versioning).
=> Fixed Fabric CCP network configs and package.json

network/sawtooth/simplenetwork/Dockerfile
=> Specify the supported sawtooth version

config/default.yaml, src/comm/logging-util.js, src/comm/util.js
Resolves Issue #338 in the recommended way.
=> Enhance logging mechanism

docs/Logging_Control.md
Corresponding documentation for PR #368
=> Add logging control documentation

src/comm/bench-flow.js
=> enable test round spec if runDuration

docs/Rate_Controllers.md
Documentation for the new features of PR #372
=> Update rate controller documentation with the new API

src/comm/client/local-client.js, src/comm/rate-control/compositeRate.js, src/comm/rate-control/fixedFeedbackRate.js, src/comm/rate-control/fixedRate.js, src/comm/rate-control/linearRate.js, src/comm/rate-control/noRate.js, src/comm/rate-control/pidRate.js, src/comm/rate-control/rateControl.js, src/comm/rate-control/rateInterface.js, src/comm/rate-control/recordRate.js, src/comm/rate-control/replayRate.js
Resolves enhancement issue #340 as suggested.
Also consolidates the API/implmenetations of existing rate controllers.
=> Added factory functions to the rate controllers

src/adapters/fabric/e2eUtils.js, src/adapters/fabric/fabric.js
The Network Model API name had a function name change from the beta to 1.4 release, this update reflects that change
Resolves #377
=> Update network model function name

docs/1_Getting_Started.md, docs/Burrow_Configuration.md, docs/Composer_Configuration.md, docs/Fabric_Ccp_Configuration.md, docs/Fabric_Configuration.md, docs/Iroha_Configuration.md, docs/Rate_Controllers.md, docs/Sawtooth_Configuration.md
This PR is to accompany (and follow) #405 and contains the doc changes that match the new repository structure and code flow
=> Update docs to match new package structure

packages/caliper-application/scripts/start-zoo-client.js, packages/caliper-application/scripts/zoo-service.js, packages/caliper-application/scripts/zookeeper-service.yaml, packages/caliper-core/lib/client/caliper-zoo-client.js
=> Fix zookeeper client path and provide start or stop zoo service cmd

packages/caliper-application/scripts/run-benchmark.js
=> Remove blockchain type option

docs/1_Getting_Started.md
Add some specification of running benchmarks for issue #421
=> Add installation information

packages/caliper-application/benchmark/simple/config-sawtooth-feedback.yaml, packages/caliper-application/network/sawtooth/simplenetwork/sawtooth-simple.yaml, packages/caliper-sawtooth/lib/sawtooth.js
=> Set status for each Sawtooth batch

packages/caliper-application/benchmark/drm/query.js
=> Throw new error when query but no committed transaction

packages/caliper-application/scripts/pre-requisites-check-for-linux.sh
The script `env_check.sh`  can check whethe the pre-requisites of Caliper have been installed and gives the version. @panyu4 @aklenik 
#376
=> add environment check script

packages/caliper-application/network/iroha/simplenetwork/docker-compose.yml, packages/caliper-application/network/iroha/simplenetwork/genesis.block, packages/caliper-application/network/iroha/simplenetwork/iroha.json, packages/caliper-application/network/iroha/simplenetwork/node1/config.sample, packages/caliper-iroha/lib/iroha.js
This PR adds the number of nodes from one to two in the iroha network. The test is good in my local repo.
@panyu4
=> add two nodes' iroha network

packages/caliper-application/scripts/run-benchmark.js, packages/caliper-core/lib/client/caliper-local-client.js, packages/caliper-core/lib/monitor/monitor.js, packages/caliper-core/lib/rate-control/fixedBacklog.js, packages/caliper-core/lib/rate-control/fixedRate.js, packages/caliper-core/lib/rate-control/rateControl.js, packages/caliper-fabric/lib/e2eUtils.js
Code update for fixed backlog rate controller
- simplified the controller logic to drive a target backlog
Whilst there also fixed a few niggles due to logger output and linting errors
=> Update backlog rate controller

packages/caliper-fabric/lib/util.js, packages/caliper-fabric/package.json
=> fix requirements for fabric1.2

.travis/script.sh
=> Remove t options in travis tests

docs/architecture_CH.md
=> Translate arch md

packages/caliper-application/benchmark/simple/config-iroha.yaml, packages/caliper-application/network/iroha/simplenetwork/iroha.json, packages/caliper-application/src/contract/iroha/simple/factory.js, packages/caliper-application/src/contract/sawtooth/smallbank/SmallBankBatchBuilder.js, packages/caliper-iroha/lib/iroha.js
1.  refactor the code to 'async/await'; 2. the property `context` is modified to the property of iroha class; 3. modify the function `sendTransactions` to `sendTransactions` and `sendTransaction`;
=> refactor iroha adaptor

CONTRIBUTING.md, README.md, packages/caliper-application/README.md
closes #447 and also modifies readme files to point to rocket chat for Caliper, and other SUT channels.
=> update readme files and contributing guide

docs/CONTRIBUTING.md, docs/Fabric_Ccp_Configuration.md, docs/Logging_Control.md, docs/Rate_Controllers.md, docs/Writing_Adapters.md, docs/Writing_Benchmarks.md
Modification of main docs to match changes made in #451, as well as fixes bad paths missed during the packaging restructure
=> update docs to match readme PR

docs/Fabric_Ccp_Configuration.md, docs/Runtime_Configuration.md
=> Add runtime configuration doc

packages/caliper-core/lib/caliper-flow.js, packages/caliper-core/lib/client/caliper-local-client.js, packages/caliper-core/lib/config/Config.js, packages/caliper-core/lib/config/config-util.js, packages/caliper-core/lib/config/default.yaml, packages/caliper-core/lib/utils/logging-util.js, packages/caliper-fabric-ccp/lib/fabric.js
Resolves Issue #339 and #422 (for the Fabric CCP adapter)
Related docs PR: #460
=> Enhanced runtime configuration support

packages/caliper-application/benchmark/simple/config.yaml, packages/caliper-application/benchmark/simple/transfer.js, packages/caliper-application/src/contract/fabric/simple/node/simpletest.js
-  error when trying the transfer method for the first time
- benchmark "benchmark/simple/transfer.js" in "benchmark/simple/config.yaml" withtout the fix
=> it will output a recurring error.
=> Issue with transferring money in "simpletest.js"

docs/1_Getting_Started.md, docs/CONTRIBUTING.md, docs/Composer_Configuration.md, docs/Writing_Adapters.md
Caliper gh-pages PR to match changes in PR #468 
Resolves #419
- Updated paths referring to calliper-application
- Updated Getting started to drive uses through the Caliper CLI commands
=> Update docs for caliper CLI

packages/caliper-samples/README.md
I neglected the edit of the samples readme to run samples based on CLI commands ... this fixes that omission!
=> update samples readme to be CLI based

packages/caliper-samples/src/contract/composer/basic-sample-network/package.json, packages/caliper-samples/src/contract/composer/bond-network/package.json, packages/caliper-samples/src/contract/composer/digitalproperty-network/package.json, packages/caliper-samples/src/contract/composer/marbles-network/package.json, packages/caliper-samples/src/contract/composer/perishable-network/package.json, packages/caliper-samples/src/contract/composer/vehicle-lifecycle-network/package.json
Fix identified vulnerabilities in eslint version ... bump version to recommended
=> update eslint due to scan check vulnerability

packages/caliper-core/lib/caliper-flow.js, packages/caliper-core/lib/test/defaultTest.js
=> Fix undefined monitor reference

packages/caliper-core/lib/client/caliper-local-client.js
Fix the problem that caliper-local-client doesn't send transactions averagely when use fixed-rate controller
https://github.com/hyperledger/caliper/issues/505
1. Install Caliper and Caliper CLI
2. Configure benchmark to use fixed-rate controller 
3. Configure the fixed-rate controller to send transactions at a high QPS
4. Run benchmark and view network utilization.
Push I/O tasks to` immediate queue` of NodeJS's event loop, so I/O tasks can be executed in prior of `Promise` tasks. For more detail principle you can refer to: [Node.js: How even quick async functions can block the Event-Loop, starve I/O](https://snyk.io/blog/nodejs-how-even-quick-async-functions-can-block-the-event-loop-starve-io/)
Before fixing, the network utilization is:
After fixing:
None.
None.
=> Fix the problem that caliper-local-client doesn't send transactions averagely

packages/caliper-tests-integration/README.md, packages/caliper-tests-integration/package.json, packages/caliper-tests-integration/scripts/cleanup.sh, packages/caliper-tests-integration/scripts/install-packages.sh, packages/caliper-tests-integration/scripts/npm_install.js, packages/caliper-tests-integration/scripts/npm_publish.js, packages/caliper-tests-integration/scripts/publish-packages.sh, packages/caliper-tests-integration/scripts/run-tests.sh, packages/caliper-tests-integration/scripts/start-verdaccio.sh
Resolves #501 
(And might make debugging #478 easier)
See the [readme](https://github.com/aklenik/caliper/blob/modularize-scripts/packages/caliper-tests-integration/README.md) for details.
=> Split publishing and installation into multiple steps

docs/1_Getting_Started.md
Corresponding documentation for #502
=> Reference install guideline from master branch

docs/Rate_Controllers.md
=> Fix spelling error

docs/1_Getting_Started.md, docs/Fabric_Configuration.md
Documentation changes for #529
=> Rename Fabric-CCP related contents and file

packages/caliper-cli/lib/benchmark/lib/runBenchmark.js, packages/caliper-cli/lib/benchmark/runBenchmarkCommand.js, packages/caliper-cli/lib/zooclient/lib/startZooClient.js, packages/caliper-cli/lib/zooclient/startZooClientCommand.js, packages/caliper-cli/lib/zooservice/lib/startZooService.js, packages/caliper-cli/lib/zooservice/lib/stopZooService.js, packages/caliper-cli/lib/zooservice/startZooServiceCommand.js, packages/caliper-cli/lib/zooservice/stopZooServiceCommand.js, packages/caliper-core/lib/caliper-flow.js, packages/caliper-core/lib/client/caliper-local-client.js, packages/caliper-core/lib/config/config-util.js, packages/caliper-core/lib/config/default.yaml, packages/caliper-core/lib/utils/logging-util.js, packages/caliper-fabric/lib/fabric.js, packages/caliper-tests-integration/scripts/run-tests.sh
=> Convert CLI parameters to runtime config settings

docs/1_Getting_Started.md, docs/CONTRIBUTING.md, docs/Composer_Configuration.md, docs/Runtime_Configuration.md
=> Update docs with changed CLI parameters

packages/caliper-core/lib/rate-control/fixedBacklog.js, packages/caliper-core/test/rate-control/fixedBacklog.js
Test written for fixedBacklog rate controller. "Closes #534".
=> Add test for fixedBacklog controller

packages/caliper-core/test/rate-control/linearRate.js
Unit tests added for the linearRateController.
=> Add unit tests for linearRate Controller

packages/caliper-iroha/lib/iroha.js, packages/caliper-samples/src/contract/iroha/simple/factory.js
Iroha smart contract was trying to use an import that it had no knowledge of ... this is bad!
Modified to:
- give better error reporting in irhoa.js
- remove the offending item in the iroha contract
Resolves #548
=> fix error in iroha smart contract

CODEOWNERS, package.json
Mirror PR for #559 with lic check ignore on the new file
=> Add codeowners and ignore in lic check on new file

docs/1_Getting_Started.md
Documentation for changes in #557
=> docs for flow control

docs/Fabric_Configuration.md
Associated docs for PR #554 and issue #553
=> Update docs for using a file wallet

packages/caliper-fabric/lib/fabric.js
If performing a "caliper-flow-only-test" interaction, when using a file wallet that has been created without admin identities, the current implementation will fail, despite not needing those.
This PR conditions the fabric.js implementation surrounding wallets to:
- only look for locally stored information if *not* using a file wallet
- only build contract maps for identities listed in the wallet
The following scenarios are available:
- Perform a benchmark (standard transaction implementation)
- Perform a benchmark through a fabric gateway
- Use a file wallet to initialise users a benchmark (standard transaction implementation)
- Use a file wallet to initialise users a benchmark through a gateway
- Use file wallet to initialise …
=> restrict wallet use

packages/caliper-fabric/lib/fabricNetwork.js
The current validation stage of a (fabric) caliper network configuration prevents a few useful options now capable with the fabric adaptor in caliper:
- the exclusive use of a wallet containing admin and non-admin credentials
- the specification of a profile that is possible to use the fabric discovery service in a `--caliper-flow-only-test` mode. 
This PR conditionally relaxes these validation aspects by taking into account:
- flow operations
- presence of a file wallet being used
- desired use of service discovery
Newly added rules:
- don't validate if only running start/end script
- only permit discovery with use of a gateway
- only permit discovery in a 'only-test' mode
- if discovery (and gateway) then skip orderer presence check …
=> modify network validation for flow/wallet/discovery options

CHANGELOG.md, README.md
Added the CHANGELOG file and cleaned up the README a bit.
=> [Release 0.1.0] Add CHANGELOG.md

_config.yml, docs/vNext/Fabric_Configuration.md, docs/vNext/Runtime_Configuration.md
Relates to PR #595 
Live preview: https://aklenik.github.io/caliper/vNext/fabric-config/
=> Refactor and update network configuration doc for Fabric

docs/vNext/Architecture.md
=> Add paragraph for configuring the reporting path

docs/vNext/Logging_Control.md
=> Adjusted logging doc page to the new features

docs/vNext/Logging_Control.md
=> Update log formatting docs

.travis.yml, scripts/check-package-names.sh
=> Add package name checking to CI

docs/vNext/Ethereum_Configuration.md
Add new config fields and note that Besu also runs under caliper.
1.
2.
3.
4.
=> Add Besu to Ethereum Docs

packages/caliper-cli/lib/bind/config.yaml, packages/caliper-fisco-bcos/lib/common.js, packages/caliper-fisco-bcos/lib/fiscoBcos.js, packages/caliper-fisco-bcos/lib/fiscoBcosApi.js, packages/caliper-fisco-bcos/lib/fiscoBcosClientWorker.js, packages/caliper-fisco-bcos/lib/generateRawTransactions.js, packages/caliper-fisco-bcos/lib/installSmartContract.js, packages/caliper-fisco-bcos/lib/invokeSmartContract.js, packages/caliper-fisco-bcos/lib/sendRawTransactions.js, packages/caliper-fisco-bcos/package.json
=> Fix FISCO BCOS package dep error

docs/vNext/FISCO_BCOS_Configuration.md, index.html
Update images and links on landing page
Update formatting of FISCO adaptor docs page
=> update landing page images and format FISCO page

packages/caliper-core/test/rate-control/noRate.js
Add test for the 'noRate' rate controller
=> NoRate controller test

packages/caliper-ethereum/lib/ethereum.js, packages/caliper-samples/network/besu/1node-clique/ethereum.json, packages/caliper-tests-integration/besu_tests/networkconfig.json
Allow the ethereum configuration to specify the gas values that each
method call is allotted.
Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>
=> Hard coded ethereum gas values

docs/vNext/Architecture.md
Corresponding docs for PR #639
=> Update round configuration docs

packages/caliper-core/test/worker/rate-control/fixedFeedbackRate.js
Test for fixed feedback rate controller.
=> Fixed feedback rate controller test

index.html
=> Fix doc typo

packages/caliper-generator/generator-caliper/.editorconfig, packages/caliper-generator/generator-caliper/.eslintignore, packages/caliper-generator/generator-caliper/.yo-rc.json, packages/caliper-generator/generator-caliper/README.md, packages/caliper-generator/generator-caliper/generators/app/index.js, packages/caliper-generator/generator-caliper/generators/benchmark/index.js, packages/caliper-generator/generator-caliper/generators/benchmark/templates/callback.js, packages/caliper-generator/generator-caliper/generators/benchmark/templates/config.yaml, packages/caliper-generator/generator-caliper/package.json, packages/caliper-generator/generator-caliper/test/benchmark/callback.js, packages/caliper-generator/generator-caliper/test/benchmark/config.js
Add Yeoman generator which generates the configuration and callback files used to perform benchmarks on deployed smart contracts.
=> Yeoman generator for benchmarking

docs/vNext/Benchmark_Generator.md
Documentation for the Yeoman generator for Caliper benchmarks.
=> Docs for the benchmark generator

docs/vNext/MonitorsAndObservers.md
Documentation for new charting option within PR #650 
=> add charting docs

packages/caliper-generator/generator-caliper/generators/benchmark/index.js
=> add when() function to rateController prompt

packages/caliper-generator/generator-caliper/generators/benchmark/index.js, packages/caliper-generator/generator-caliper/generators/benchmark/templates/config.yaml, packages/caliper-generator/generator-caliper/package.json, packages/caliper-generator/generator-caliper/test/benchmark/config.js
=> Add features to allow generator options from cmd line

packages/caliper-generator/generator-caliper/generators/benchmark/index.js, packages/caliper-generator/generator-caliper/generators/benchmark/templates/callback.js, packages/caliper-generator/generator-caliper/test/benchmark/callback.js, packages/caliper-generator/generator-caliper/test/benchmark/config.js
Add a prompt for smart contract arguments to the generator.
=> Add prompt for smart contract variables to generator

packages/caliper-tests-integration/fabric_tests/phase3/src/marbles/go/marbles.go, packages/caliper-tests-integration/fabric_tests/phase3/src/marbles/node/marbles.js
Add to Init methods in go and node smart contracts to create marbles on initialization.
=> Initalize contract with marbles

.travis.yml, .travis/benchmark-integration-test-direct.sh, .travis/benchmark-integration-test-verdaccio.sh, .travis/checks-and-unit-tests.sh, .travis/docker-publish.sh, .travis/npm-publish.sh, lerna.json, package.json, packages/caliper-burrow/package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-iroha/package.json, packages/caliper-sawtooth/package.json, packages/caliper-tests-integration/package.json, packages/caliper-tests-integration/run-tests.sh, packages/caliper-tests-integration/scripts/buildDockerImage.js, packages/caliper-tests-integration/scripts/utils/cmdutils.js
Experimenting with the CI process a bit. The goal is to add npm and docker publishing as the final CI stages.
=> Refactor CI build stages (basic tests, integration tests, publishing)

.travis.yml, .travis/build-info.sh
Hopefully, the problem with the previous PR was the incorrect repo (my fork) when encrypting the tokens.
=> Generate encrypted tokens with correctly set repository

packages/caliper-generator/generator-caliper/generators/benchmark/index.js, packages/caliper-generator/generator-caliper/generators/benchmark/templates/config.yaml, packages/caliper-generator/generator-caliper/test/benchmark/config.js
=> changes made to config.yaml template file

packages/caliper-generator/generator-caliper/package.json
=> Include Hyperledger namespace in package.json

docs/vNext/Benchmark_Generator.md
=> Generator docs to include Hyperledger namespace

packages/caliper-fisco-bcos/README.md, packages/caliper-fisco-bcos/package.json
=> Add readme for FISCO adapter

.travis.yml, .travis/benchmark-integration-test-direct.sh, .travis/build-info.sh, .travis/checks-and-unit-tests.sh, .travis/docker-publish.sh, .travis/npm-publish.sh
It seems that secret env variables are not available yet when the stage conditions are evaluated. So the checks have been moved inside the stage scripts.
=> Move CI stage conditions inside the scripts

docs/vNext/Logging_Control.md, docs/vNext/Messengers.md
Documentation for possible messenger implementations between the orchestrator and workers
=> Document the messenger use

docs/vNext/Rate_Controllers.md
Modify the fixed backlog rate controller documentation to apply changes made in PR #704
=> Documentation for fixed backlog controller

.travis.yml
=> Fix build conditions and remove sudo requirement

CONTRIBUTING.md
Signed-off-by: Seonpyo Kim <spkim@kodebox.io>
=> Add caliper-ethereum to the adaptor list

docs/vNext/Installing_Caliper.md
=> Update install page with versioning semantics and fix examples

.travis.yml
Current travis build specification prevents a valid local travis (linked personal repository) builds.
Proposed changes adds an additional condition such that the behaviour is also conditioned on the github repository
=> Enable local travis builds

docs/vNext/Runtime_Configuration.md
Uses the CLI commands of #742 
* Updated the examples (package name and CLI commands)
* Restructured some parts (ToC, Overview, Licence)
* Added descriptions for the available runtime configuration keys
=> Updated the runtime configuration page and added default setting descriptions

docs/vNext/Architecture.md, docs/vNext/BenchmarkConfiguration.md, docs/vNext/architecture_CH.md
First of the PRs that will rework the architecture doc page and structure the content a bit.
=> Split benchmark configuration from architecture doc

docs/vNext/Architecture.md, docs/vNext/Workload_Module.md
=> Split workload modules from architecture docs

CHANGELOG.md, lerna.json, package.json, packages/caliper-burrow/package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-generator/generator-caliper/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-iroha/package.json, packages/caliper-publish/package.json, packages/caliper-sawtooth/package.json, packages/caliper-tests-integration/package.json
=> [Release v0.3.0] Bump package versions and update changelog

lerna.json, package.json, packages/caliper-burrow/package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-generator/generator-caliper/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-iroha/package.json, packages/caliper-publish/package.json, packages/caliper-sawtooth/package.json, packages/caliper-tests-integration/package.json
Following release - we need the tags reverted to be marked unstable
=> bump version tags to unstable

packages/caliper-cli/package.json, packages/caliper-publish/package.json
Closes #768 
update the version of yargs being used.
=> update yargs to 15.3.1

packages/caliper-core/lib/common/utils/caliper-utils.js, packages/caliper-fabric/lib/fabric.js
Closes #766 and #765 
Modifies the package check within the fabric adaptor
=> modify package check to prevent throwing

packages/caliper-tests-integration/fabric_tests/run.sh
Seems the flag change didn't make it into the integration tests:
- modified flag to use the gateway mode
=> change gateway flag in test

docs/vLatest/BenchmarkConfiguration.md, docs/vNext/BenchmarkConfiguration.md
=> Update the benchmark configuration schema docs to 0.3.0

packages/caliper-core/lib/worker/client/caliper-local-client.js
closes #778 
Implement suggested code mod so that cb.end() has access to the context.
=> move location of cb.end()

docs/vLatest/Installing_Caliper.md, docs/vNext/Installing_Caliper.md
=> Fix version numbers in install doc pages

packages/caliper-sawtooth/.eslintrc.yml, packages/caliper-sawtooth/lib/helpers/sawtooth-helper.js, packages/caliper-sawtooth/lib/sawtooth.js
=> covert sawtooth adaptor to class

packages/caliper-cli/lib/lib/config.yaml
Sigh, missing leading quote within fabric binding
=> Fix missing quote

packages/caliper-tests-integration/fabric_docker_distributed_tests/package.json, packages/caliper-tests-integration/fabric_docker_local_tests/package.json
License must be Apache 2
https://jira.hyperledger.org/projects/LSI/issues/LSI-25
=> LSI-25: Fix license

.gitignore, CODEOWNERS, CODE_OF_CONDUCT.md, MAINTAINERS.md, package.json, packages/caliper-cli/.gitignore, packages/caliper-core/.gitignore, packages/caliper-fabric/.gitignore, packages/caliper-iroha/.gitignore, packages/caliper-publish/.gitignore, repolint.json
Hyperledger Foundation requirement to have repolinter in the repository to enforce common structures
=> Add repolinter and core required files

packages/caliper-ethereum/package.json
Signed-off-by: Ben Burns <803016+benjamincburns@users.noreply.github.com>
=> ethereum: revert erroneous change to web3 dependency for ethereum adapter

docs/vNext/Ethereum_Configuration.md
Also includes some very small grammar and changes to the order of existing paragraphs to improve flow/readability.
Signed-off-by: Ben Burns <803016+benjamincburns@users.noreply.github.com>
=> ethereum config: document websocket and gas limit changes

CHANGELOG.md, lerna.json, package.json, packages/caliper-burrow/package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-generator/generator-caliper/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-iroha/package.json, packages/caliper-publish/package.json, packages/caliper-sawtooth/package.json, packages/caliper-tests-integration/package.json
=> [Release 0.3.1] Bump package versions and update change log

lerna.json, package.json, packages/caliper-burrow/package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-generator/generator-caliper/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-iroha/package.json, packages/caliper-publish/package.json, packages/caliper-sawtooth/package.json, packages/caliper-tests-integration/package.json
=> Bump packages to unstable version

packages/caliper-generator/generator-caliper/README.md, packages/caliper-publish/lib/impl/npm.js
Relates to issue #832 
add the `caliper-generator` package to the list of packages in `caliper-publish`
=> Publish caliper generator

packages/caliper-publish/lib/impl/npm.js
=> Publish generator-caliper

packages/caliper-publish/lib/impl/npm.js
Master build broken due to publish failure of generator - prevent failing publish
=> revert publish of generator

packages/generator-caliper/package.json
Remove private attribute from generator-package package.json file
=> Remove private attribute

packages/caliper-cli/lib/lib/config.yaml, packages/caliper-tests-integration/fabric_tests/run.sh
Binding for `fabric-sdk-node:1.4.8`
Bumped the version bound to in the integration test too
=> 0.3.2 release candidate: Add 1.4.8 binding

_config.yml, _includes/v0.2.html, _includes/v0.3.2.html, _includes/v0.3.html, _includes/vNext.html, _layouts/v0.3.2.html, docs.json, docs/v0.3.2/Architecture.md, docs/v0.3.2/BenchmarkConfiguration.md, docs/v0.3.2/Benchmark_Generator.md, docs/v0.3.2/Burrow_Configuration.md, docs/v0.3.2/CONTRIBUTING.md, docs/v0.3.2/Caliper_FAQ.md, docs/v0.3.2/Ethereum_Configuration.md, docs/v0.3.2/FISCO_BCOS_Configuration.md, docs/v0.3.2/Fabric_Configuration.md, docs/v0.3.2/Getting_Started.md, docs/v0.3.2/Installing_Caliper.md, docs/v0.3.2/Iroha_Configuration.md, docs/v0.3.2/LICENSE.md, docs/v0.3.2/Logging_Control.md, docs/v0.3.2/Messengers.md, docs/v0.3.2/MonitorsAndObservers.md, docs/v0.3.2/Rate_Controllers.md, docs/v0.3.2/Runtime_Configuration.md, docs/v0.3.2/Sawtooth_Configuration.md, docs/v0.3.2/Workload_Module.md, docs/v0.3.2/Writing_Adapters.md, docs/v0.3.2/Writing_Benchmarks.md, docs/v0.3.2/architecture_CH.md
=> v0.3.2 release docs

docs/vNext/Rate_Controllers.md
companion PR for #874 and closes #870
Docs for max rate controller use
=> Docs for max rate controller

.travis.yml, packages/caliper-core/lib/master/orchestrators/round-orchestrator.js, packages/caliper-core/lib/worker/caliper-worker.js, packages/caliper-publish/lib/impl/npm.js, packages/caliper-tests-integration/besu_tests/phase2/benchconfig.yaml, packages/caliper-tests-integration/besu_tests/phase3/benchconfig.yaml, packages/caliper-tests-integration/ethereum_tests/benchconfig.yaml, packages/caliper-tests-integration/fabric_docker_distributed_tests/benchconfig.yaml, packages/caliper-tests-integration/fabric_docker_local_tests/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase1/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase2/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase3/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase4/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase5/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase6/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase7/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/run.sh, packages/caliper-tests-integration/fisco-bcos_tests/benchconfig.yaml, packages/caliper-tests-integration/iroha_tests/benchconfig.yaml, packages/caliper-tests-integration/sawtooth_tests/benchconfig.yaml
=> Refactor workload-related benchmark config schema

packages/caliper-core/lib/master/report/report-builder.js, packages/caliper-tests-integration/besu_tests/caliper.yaml
Closes #876 
The Besu test showcases the feature/fix.
=> Create report directory if does not exist

docs/vNext/Benchmark_Generator.md, docs/vNext/Caliper_FAQ.md, docs/vNext/Ethereum_Configuration.md, docs/vNext/Fabric_Configuration.md, docs/vNext/Runtime_Configuration.md
Contributes to #871 
Document companion for PR #891
- Update vNext to reflect changes in chaincode/contract use
=> Update docs for chaincode -> contract change

docs/vNext/BenchmarkConfiguration.md, docs/vNext/Workload_Module.md
=> Update workload module-related docs

docs/v0.3.2/Architecture.md, docs/v0.3.2/MonitorsAndObservers.md, docs/vNext/Architecture.md
=> Fix connector usage and references

docs/vNext/Ethereum_Configuration.md, docs/vNext/FISCO_BCOS_Configuration.md, docs/vNext/Fabric_Configuration.md, docs/vNext/Workload_Module.md
=> Remove context argument from connector API examples

docs/vNext/Rate_Controllers.md
Companion docs change for #909 
=> update vNext docs for rate controller property change

docs/v0.3.2/Benchmark_Generator.md
=> Fix generator run command in Caliper docs

docs/vNext/Fabric_Configuration.md
Contributes to #898
Companion docs for #916 
=> docs for organization wallets

docs/vNext/Fabric_Configuration.md
=> Docs for optional channel name in invoke/query settings

MAINTAINERS.md
now includes:
- active/retired maintainers
- contributors with code package familiarity
=> update maintainers list

README.md, _includes/vNext.html, docs/vNext/Tutorial_placeholder.md
=> Added tutorial placeholder

packages/caliper-cli/lib/lib/config.yaml, packages/caliper-fabric/lib/connector-versions/v1/fabric-gateway.js, packages/caliper-fabric/lib/connector-versions/v1/fabric.js, packages/caliper-fabric/lib/connector-versions/v2/fabric-gateway.js, packages/caliper-fabric/lib/connector-versions/v2/fabric.js
=> Add Support for targetOrganizations for fabric connector

docs/vNext/Fabric_Configuration.md, docs/vNext/Installing_Caliper.md
Update the docs for support for targetOrganizations
closes #919 
=> update docs for targetOrgs

docs/vNext/MonitorsAndObservers.md, docs/vNext/Rate_Controllers.md, docs/vNext/Runtime_Configuration.md
Companion PR for #943 
Visible direct at: https://nklincoln.github.io/caliper/
Main changes: 
- Monitors/Observers page
- Rate controllers (renamed fixed-feedback and updated camel case parameters)
- New config setting for enabling runtime txn numbers
=> docs for txobservers

packages/caliper-fabric/lib/ConnectorConfiguration.js, packages/caliper-fabric/lib/ConnectorConfigurationFactory.js, packages/caliper-fabric/test/ConnectorConfigurationFactory.js
Add a factory implementation
Contributes to #940
=> Add factory

packages/caliper-burrow/lib/burrow-connector.js, packages/caliper-core/lib/common/core/blockchain-connector.js, packages/caliper-core/lib/worker/caliper-worker.js, packages/caliper-ethereum/lib/ethereum-connector.js, packages/caliper-fabric/lib/connector-versions/v1/fabric-gateway.js, packages/caliper-fabric/lib/connector-versions/v1/fabric.js, packages/caliper-fabric/lib/connector-versions/v2/fabric-gateway.js, packages/caliper-fabric/lib/fabric-connector.js, packages/caliper-fisco-bcos/lib/fiscoBcos-connector.js, packages/caliper-tests-integration/besu_tests/open.js, packages/caliper-tests-integration/besu_tests/query.js, packages/caliper-tests-integration/besu_tests/transfer.js, packages/caliper-tests-integration/ethereum_tests/open.js, packages/caliper-tests-integration/ethereum_tests/query.js, packages/caliper-tests-integration/ethereum_tests/transfer.js, packages/caliper-tests-integration/fabric_docker_distributed_tests/init.js, packages/caliper-tests-integration/fabric_docker_distributed_tests/query.js, packages/caliper-tests-integration/fabric_docker_local_tests/init.js, packages/caliper-tests-integration/fabric_docker_local_tests/query.js, packages/caliper-tests-integration/fabric_tests/init.js, packages/caliper-tests-integration/fabric_tests/initByChannel.js, packages/caliper-tests-integration/fabric_tests/query.js, packages/caliper-tests-integration/fabric_tests/queryByChannel.js, packages/caliper-tests-integration/fisco-bcos_tests/get.js, packages/caliper-tests-integration/fisco-bcos_tests/set.js, packages/generator-caliper/generators/benchmark/templates/workload.js, packages/generator-caliper/test/benchmark/workload.js
- Simplify TX batch processing
- Extract new sendRequests function into base class
- Update CI workload modules and tests
- Halt execution on unhandled error
Finally closes #888 🙂 
=> Merge connector invoke/query API functions

packages/caliper-fabric/lib/ConnectorConfiguration.js, packages/caliper-fabric/test/ConnectorConfiguration.js, packages/caliper-fabric/test/utils/GenerateConfiguration.js
Add isMutualTLS support to new fabric connector configuration
=> add isMutualTLS support

packages/caliper-core/lib/worker/rate-control/fixedFeedbackRate.js, packages/caliper-core/lib/worker/rate-control/maxRate.js
Picks off the last of the rate controller changes, no docs updates required 🎉 
Closes #911
=> remove underscore vars and client refs

docs/vNext/MonitorsAndObservers.md
=> add docs for prom tx observer

packages/caliper-fabric/lib/ConnectorConfiguration.js, packages/caliper-fabric/test/ConnectorConfiguration.js, packages/caliper-fabric/test/utils/GenerateConfiguration.js
=> Add support to retrieve channel creation information

docs/vNext/MonitorsAndObservers.md
Companion docs change for #966 
=> Docs for modified prometheus push

packages/caliper-fabric/lib/ConnectorConfiguration.js, packages/caliper-fabric/test/ConnectorConfiguration.js
=> Add getAllChannelNames support

packages/caliper-cli/lib/bindCommand.js, packages/caliper-cli/lib/launch/launchManagerCommand.js, packages/caliper-cli/lib/launch/launchWorkerCommand.js, packages/caliper-cli/lib/lib/config.yaml, packages/caliper-cli/lib/unbindCommand.js, packages/caliper-tests-integration/fabric_docker_distributed_tests/config/generate.sh, packages/caliper-tests-integration/fabric_docker_distributed_tests/docker-compose.yaml, packages/caliper-tests-integration/fabric_docker_local_tests/config/generate.sh, packages/caliper-tests-integration/fabric_docker_local_tests/docker-compose.yaml, packages/caliper-tests-integration/fabric_docker_local_tests/src/marbles/node/package.json, packages/caliper-tests-integration/fabric_tests/config/generate.sh, packages/caliper-tests-integration/fabric_tests/docker-compose.yaml, packages/caliper-tests-integration/fabric_tests/phase3/src/marbles/node/package.json, packages/caliper-tests-integration/fabric_tests/run.sh, packages/caliper-tests-integration/generator_tests/fabric/config/generate.sh, packages/caliper-tests-integration/generator_tests/fabric/docker-compose.yaml, packages/caliper-tests-integration/generator_tests/fabric/run.sh, packages/caliper-tests-integration/generator_tests/fabric/src/marbles/node/package.json
updates node-sdks and fabric images to the current latest versions
=> Move fabric versions to latest

packages/caliper-fabric/lib/connector-versions/v1/fabric-gateway.js
For a gateway implementation it cannot support event compatibility mode
because the old event hub implementation was removed in 1.4 node-sdk.
The gateway implementation should not be used against fabrics prior to
1.4 either that would still have the old peer implementation of the
eventhub as 1.4 SDKs only support 1.4 fabrics and all SUTs prior to 1.4
have been removed in caliper
This PR removes the redundant code as it will never be used
=> Remove redundant event code from v1 gateway

packages/caliper-cli/lib/lib/config.yaml, packages/caliper-core/lib/common/utils/caliper-utils.js
=> fix SUT and error reporting

packages/caliper-fabric/lib/identity-management/ExportedIdentity.js, packages/caliper-fabric/lib/identity-management/IWalletFacade.js, packages/caliper-fabric/lib/identity-management/IWalletFacadeFactory.js, packages/caliper-fabric/lib/identity-management/IdentityManager.js, packages/caliper-fabric/lib/identity-management/IdentityManagerFactory.js, packages/caliper-fabric/package.json, packages/caliper-fabric/test/identity-management/IdentityManager.js, packages/caliper-fabric/test/sampleConfigs/BasicConfig.json, packages/caliper-fabric/test/sampleConfigs/BasicConfig.yaml
This PR provides a framework for the initial implementation for how identities will be handled in the new fabric configuration
=> Initial IdentityManager impl

docs/vNext/MonitorsAndObservers.md
Contributes to #964
- companion docs for #974
=> Docs: Update resource monitor for prometheus

packages/caliper-fabric/lib/connector-configuration/ConnectorConfiguration.js, packages/caliper-fabric/test/connector-configuration/ConnectorConfiguration.js
=> Add support for getting contract details

docs/vNext/Architecture.md, docs/vNext/Ethereum_Configuration.md, docs/vNext/Fabric_Configuration.md, docs/vNext/Getting_Started.md, docs/vNext/Installing_Caliper.md, docs/vNext/Runtime_Configuration.md, docs/vNext/Workload_Module.md, docs/vNext/Writing_Connectors.md
- Write detailed docs about how to implement connectors
- Update connector-specific pages based on the new API
- Fix minor inconsistencies in other pages
Live preview: https://aklenik.github.io/caliper/
Relates to #1006 
Closes #963 
=> Update connector documentation

packages/caliper-fabric/lib/connector-configuration/ConnectionProfileDefinition.js, packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js
=> Add support for isTLSEnabled

docs/vNext/Fabric_Configuration.md, docs/vNext/Installing_Caliper.md
Companion docs change for #1021 
=> remove references to removed sdk bindings

docs/v0.3.2/tutorials_fabric_existing.md, docs/vNext/Fabric_Tut.html, docs/vNext/Tutorial_placeholder.md, docs/vNext/tutorials_fabric_existing.md
closes #962 
- updates vNext tutorial for v0.4-unstable 
Available for view on https://nklincoln.github.io/caliper/vNext/fabric-tutorial/
=> Update Fabric tutorial for 0.4.0

_config.yml, _includes/v0.3.2.html, _includes/v0.4.0.html, _includes/vNext.html, _layouts/v0.4.0.html, docs/v0.4.0/Architecture.md, docs/v0.4.0/BenchmarkConfiguration.md, docs/v0.4.0/Benchmark_Generator.md, docs/v0.4.0/CONTRIBUTING.md, docs/v0.4.0/Caliper_FAQ.md, docs/v0.4.0/Ethereum_Configuration.md, docs/v0.4.0/FISCO_BCOS_Configuration.md, docs/v0.4.0/Fabric_Configuration.md, docs/v0.4.0/Fabric_Tut.html, docs/v0.4.0/Getting_Started.md, docs/v0.4.0/Installing_Caliper.md, docs/v0.4.0/LICENSE.md, docs/v0.4.0/Logging_Control.md, docs/v0.4.0/Messengers.md, docs/v0.4.0/MonitorsAndObservers.md, docs/v0.4.0/Rate_Controllers.md, docs/v0.4.0/Runtime_Configuration.md, docs/v0.4.0/Workload_Module.md, docs/v0.4.0/Writing_Connectors.md, docs/v0.4.0/tutorials_fabric_existing.md
Docs bump to v0.4.0
preview available https://nklincoln.github.io/caliper/v0.4.0/getting-started/
=> Bump docs to v0.4.0

lerna.json, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
=> [Release v0.4.0] Bump version to stable v0.4.0

lerna.json, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
=> Bump version to unstable v0.5.0

packages/caliper-fabric/lib/connector-versions/v2/WalletFacade.js, packages/caliper-fabric/lib/connector-versions/v2/WalletFacadeFactory.js, packages/caliper-fabric/lib/identity-management/IdentityManager.js, packages/caliper-fabric/test/connector-versions/v2/GatewayStubs.js, packages/caliper-fabric/test/connector-versions/v2/WalletFacade.js
1. move the wallet stubs out into a separate file
2. include future stubs required for new connector testing
3. add check into addToWallet impl to detect same alias name
=> Minor improvements to V2 Wallet Impl

packages/caliper-fabric/lib/FabricConnectorContext.js, packages/caliper-fabric/lib/FabricConnectorFactory.js, packages/caliper-fabric/lib/connector-versions/v1/fabric-gateway.js, packages/caliper-fabric/lib/connector-versions/v1/fabric.js, packages/caliper-fabric/lib/connector-versions/v2/FabricGateway.js, packages/caliper-fabric/lib/connector-versions/v2/fabric-gateway.js, packages/caliper-fabric/package.json, packages/caliper-fabric/test/FabricConnectorFactory.js, packages/caliper-fabric/test/connector-versions/v2/FabricGateway.js, packages/caliper-fabric/test/sample-configs/BasicConfig.json, packages/caliper-fabric/test/sample-configs/BasicConfig.yaml, packages/caliper-fabric/test/sample-configs/LegacyNetworkConfig.yaml, packages/caliper-fabric/test/sample-configs/NoIdentitiesNetworkConfig.yaml
1. support both old and new connectors to allow for easier PR delivery
2. refactored and simplified
=> New fabric connector factory

packages/caliper-tests-integration/fabric_tests/init.js, packages/caliper-tests-integration/fabric_tests/initByChannel.js, packages/caliper-tests-integration/fabric_tests/phase6/ccp-org1.yaml, packages/caliper-tests-integration/fabric_tests/phase6/ccp-org2.yaml, packages/caliper-tests-integration/fabric_tests/phase6/networkconfig-legacy.yaml, packages/caliper-tests-integration/fabric_tests/phase6/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/query.js, packages/caliper-tests-integration/fabric_tests/queryByChannel.js, packages/caliper-tests-integration/fabric_tests/run.sh
=> Add new connector to integration tests

docs/v0.4.0/Installing_Caliper.md, docs/vNext/Installing_Caliper.md
Update available SDKs within bindings
closes #1046 
=> update avaiable internal bindings

packages/caliper-publish/caliper.Dockerfile
closes #1049 
Move to v10.22 node in caliper image 
=> Update node version in image

packages/caliper-fabric/lib/connector-configuration/ConnectionProfileDefinition.js, packages/caliper-fabric/lib/connector-configuration/ConnectorConfiguration.js, packages/caliper-fabric/lib/connector-versions/v1/ClientCreator.js, packages/caliper-fabric/lib/connector-versions/v1/FabricGateway.js, packages/caliper-fabric/lib/connector-versions/v2/FabricGateway.js, packages/caliper-fabric/lib/identity-management/IdentityManager.js, packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js, packages/caliper-fabric/test/connector-configuration/ConnectorConfiguration.js, packages/caliper-fabric/test/connector-versions/v1/ClientCreator.js, packages/caliper-fabric/test/connector-versions/v1/ClientStub.js, packages/caliper-fabric/test/connector-versions/v1/V1GatewayStubs.js, packages/caliper-fabric/test/identity-management/IdentityManager.js, packages/caliper-fabric/test/sample-configs/NoConnectionProfileNetworkConfig.yaml, packages/caliper-fabric/test/sample-configs/StaticOrg1ConnectionProfile.json
=> Pre-req support code for V1 non gateway fabric connector

packages/caliper-fabric/test/identity-management/IdentityManager.js
=> Improve readibility and behaviour of Identity Manager tests

packages/caliper-core/lib/common/core/transaction-statistics-collector.js, packages/caliper-core/test/common/core/transaction-statisitcs-collector.js
closes #1044 
Fixes bug and add unit tests
=> Update txCollector and add unit tests

CHANGELOG.md
=> Update changelog for 0.4.1

lerna.json, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
Official release version bump for 0.4.1 to include:
- stats bug
- node 10.22 official docker image
1.
2.
3.
4.
=> version bump for 0.4.1 release

lerna.json, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
bump versions to 0.4.2-unstable
=> update version to unstable

packages/caliper-fabric/lib/connector-configuration/ConnectorConfiguration.js, packages/caliper-fabric/lib/connector-versions/v2/FabricGateway.js, packages/caliper-fabric/lib/connector-versions/v2/fabric-gateway.js, packages/caliper-fabric/lib/identity-management/IdentityManager.js, packages/caliper-fabric/test/connector-configuration/ConnectorConfiguration.js, packages/caliper-fabric/test/identity-management/IdentityManager.js, packages/caliper-fabric/test/sample-configs/BasicConfig.json, packages/caliper-fabric/test/sample-configs/BasicConfig.yaml, packages/caliper-fabric/test/sample-configs/BasicConfigWithStaticCCP.yaml, packages/caliper-fabric/test/utils/GenerateConfiguration.js
=> Added support for admin identities

packages/caliper-fabric/lib/identity-management/IdentityManager.js, packages/caliper-fabric/test/identity-management/IdentityManager.js
=> Support Single Wallet for Multiple Organizations

.gitignore, docs/vNext/FISCO_BCOS_Configuration.md, docs/vNext/Fabric_Configuration_Legacy.md, docs/vNext/Fabric_Configuration_New.md
available at https://davidkel.github.io/caliper/vNext/getting-started/
=> New Fabric connector docs

packages/caliper-cli/lib/lib/config.yaml
=> Add new SUT for fabric

CHANGELOG.md
=> [1/3] Update changelog

lerna.json, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
Required version bump for 0.4.2 release
=> [2 of 3] Bump versions for release process

_config.yml, _includes/v0.2.html, _includes/v0.3.2.html, _includes/v0.4.2.html, _includes/vNext.html, _layouts/v0.4.2.html, docs.json, docs/v0.4.2/Architecture.md, docs/v0.4.2/BenchmarkConfiguration.md, docs/v0.4.2/Benchmark_Generator.md, docs/v0.4.2/CONTRIBUTING.md, docs/v0.4.2/Caliper_FAQ.md, docs/v0.4.2/Ethereum_Configuration.md, docs/v0.4.2/FISCO_BCOS_Configuration.md, docs/v0.4.2/Fabric_Configuration_Legacy.md, docs/v0.4.2/Fabric_Configuration_New.md, docs/v0.4.2/Fabric_Tut.html, docs/v0.4.2/Getting_Started.md, docs/v0.4.2/Installing_Caliper.md, docs/v0.4.2/LICENSE.md, docs/v0.4.2/Logging_Control.md, docs/v0.4.2/Messengers.md, docs/v0.4.2/MonitorsAndObservers.md, docs/v0.4.2/Rate_Controllers.md, docs/v0.4.2/Runtime_Configuration.md, docs/v0.4.2/Workload_Module.md, docs/v0.4.2/Writing_Connectors.md, docs/v0.4.2/tutorials_fabric_existing.md
Docs release for 0.4.2
Preview available on https://nklincoln.github.io/caliper/
=> [3/3] Version bump for docs

lerna.json, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
=> bump to 0.4.3-unstable

azure-pipelines.yml
Contributes to #1102
Enables builds for PR that target master branch
Introduction of `stages` so that we can have three stages:
- unit test
- integration test
- publish (todo)
=> Enable builds for PRs that target master branch

.build/publish-docker.sh, .build/publish-npm.sh, azure-pipelines.yml
And new stage for publishing, only on:
- prior build success
- master branch
- CI build
Break out npm and docker publishing to be runnable in separate jobs
=> publish to npm stage

azure-pipelines.yml
contributes to #1102
Format yaml
Update conditional for equality
=> update pipeline condition

azure-pipelines.yml
Contributes to #1102
Update build reason to `IndividualCI`
=> Change build reason for publish

azure-pipelines.yml
Contributes to #1102
Prevent cascade skipping of publish stage when preceding stage is skipped
=> prevent cascade skip

packages/caliper-gui-dashboard/package.json
=> use 0.21.1 axios

docs/v0.4.2/Fabric_Configuration_New.md, docs/vNext/Fabric_Configuration_New.md
=> fix docs about localhost

docs/v0.4.2/Ethereum_Configuration.md, docs/vNext/Ethereum_Configuration.md
Doc changes related to value parameter for payable functions in Ethereum. Document changes related to PR #1122.
=> Doc changes related to value parameter for payable functions in Ethereum.

packages/caliper-core/lib/worker/workload/declarative/value-providers/parameter-reference-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/uniform-random-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/value-provider-interface.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/variable-reference-value-provider.js, packages/caliper-core/test/worker/workload/declarative/value-providers/parameter-reference-value-provider.test.js, packages/caliper-core/test/worker/workload/declarative/value-providers/uniform-random-value-provider.test.js, packages/caliper-core/test/worker/workload/declarative/value-providers/value-provider-interface.test.js, packages/caliper-core/test/worker/workload/declarative/value-providers/variable-reference-value-provider.test.js
- Added value-provider-interface and uniform-random-value-provider
- Added unit tests for value providers
- UniformRandomValueProvider test fix and reference value provider addition
Signed-off-by: Aastha Bist <abist119@gmail.com>
=> Added basic value providers in workload module

README.md
Add a badge to open repository in Visual Studio Code
=> Added open in Visual Studio Code badge

SECURITY.md
=> Update link for security bug handling wiki page

azure-pipelines.yml
Probably the first step to get the CI pipeline working (before debugging integration tests or porting to GitHub Actions).
=> Update branch name in Azure CI pipeline configuration

packages/caliper-core/lib/worker/workload/declarative/value-providers/formatted-string-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/list-element-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/parameter-reference-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/uniform-random-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/value-provider-factory.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/value-provider-interface.js, packages/caliper-core/test/worker/workload/declarative/value-providers/formatted-string-value-provider.test.js, packages/caliper-core/test/worker/workload/declarative/value-providers/list-element-value-provider.test.js, packages/caliper-core/test/worker/workload/declarative/value-providers/value-provider-factory.test.js
Signed-off-by: Aastha Bist <abist119@gmail.com>
=> Add factory class, formatted string and list element value providers.

packages/caliper-tests-integration/ethereum_tests/config/caliper-ethereum-clique.Dockerfile, packages/caliper-tests-integration/ethereum_tests/config/docker-compose.yml
* Anchor Ethereum client docker image version
* Fix geth CLI flags according to the set release
=> Fix Ethereum integration test

MAINTAINERS.md
I would like to request to become a new caliper maintainer based on my
contributions to caliper especially around a new fabric connector
released in 0.4.2
=> Propose myself as a new caliper Maintainer

CONTRIBUTING.md
=> Update CONTRIBUTING.md document

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml
* Add issue template for bug reports
* Add issue template for feature requests
* Still allow the old issue template for now
* Provide links to other Caliper forums
Closes #1190 
=> Add GitHub web forms-based issue templates

packages/caliper-core/index.js, packages/caliper-core/lib/worker/workload/declarative/contract-function-parameter.js, packages/caliper-core/lib/worker/workload/declarative/contract-function.js, packages/caliper-core/lib/worker/workload/declarative/contract.js, packages/caliper-core/lib/worker/workload/declarative/declarative-workload-module-base.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/formatted-string-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/list-element-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/parameter-reference-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/uniform-random-list-item-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/uniform-random-value-provider.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/value-provider-factory.js, packages/caliper-core/lib/worker/workload/declarative/value-providers/value-provider-interface.js, packages/caliper-core/test/worker/workload/declarative/contract-function-parameter.test.js, packages/caliper-core/test/worker/workload/declarative/value-providers/formatted-string-value-provider.test.js, packages/caliper-core/test/worker/workload/declarative/value-providers/list-element-value-provider.test.js, packages/caliper-core/test/worker/workload/declarative/value-providers/uniform-random-list-item-value-provider.test.js, packages/caliper-core/test/worker/workload/declarative/value-providers/value-provider-factory.test.js
- Integrate Value Providers by extending WorkloadModuleBase
- Add DeclarativeWorkloadModuleBase
=> Value provider integration

docs/vNext/Benchmark_Generator.md, docs/vNext/DeclarativeWorkloadModule.md, docs/vNext/Logging_Control.md, docs/vNext/Messengers.md, docs/vNext/MonitorsAndObservers.md, index.html
Contains declarative workload module documentation added to vNext.
=> Docs: Added Declarative Workload Module

packages/caliper-fabric/lib/connector-versions/peer-gateway/WalletFacade.js, packages/caliper-fabric/lib/connector-versions/peer-gateway/WalletFacadeFactory.js, packages/caliper-fabric/test/connector-versions/peer-gateway/WalletFacade.js
add new folder peer-gateway containing new connector Wallet Facade and Wallet Facade Factory
=> Add new connector Wallet facade and Wallet facade Fatory on the peer-gateway folder

azure-pipelines.yml, packages/caliper-core/test/common/utils/caliper-utils.js, packages/caliper-gui-dashboard/package.json
=> Add support for node 16

docs/v0.4.2/Runtime_Configuration.md, docs/vNext/Runtime_Configuration.md
=> update incorrect doc about timeout

docs/v0.4.2/Installing_Caliper.md, docs/vNext/Installing_Caliper.md
=> Update node versions for caliper

docs/v0.4.2/MonitorsAndObservers.md, docs/vNext/MonitorsAndObservers.md
=> fix the docs for specifying charts

docs/v0.4.2/BenchmarkConfiguration.md, docs/vNext/BenchmarkConfiguration.md
=> fix the benchmarks page

lerna.json, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
=> Bump version to 0.5.0-unstable

packages/caliper-fabric/lib/connector-versions/v2/FabricGateway.js, packages/caliper-fabric/test/connector-versions/v2/FabricGateway.js
=> ensure endorsetimeout is set on v2 fabric connector

packages/caliper-fabric/lib/connector-versions/v1/FabricNonGateway.js
=> add txid to proposal when doing a query

packages/caliper-fabric/lib/FabricConnectorFactory.js, packages/caliper-fabric/test/FabricConnectorFactory.js, packages/caliper-tests-integration/fabric_tests/run.sh
=> Remove the need for gateway-enabled when binding to a fabric 2.2 SUT

.build/benchmark-integration-test-direct.sh, packages/caliper-cli/lib/lib/config.yaml, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-tests-integration/besu_tests/run.sh, packages/caliper-tests-integration/ethereum_tests/run.sh, packages/caliper-tests-integration/fabric_tests/run.sh, packages/caliper-tests-integration/fisco-bcos_tests/run.sh, packages/caliper-tests-integration/generator_tests/fabric/run.sh
This should address #1243 and hopefully will also make the builds a little bit quicker
=> Improve integration tests

packages/caliper-fabric/lib/identity-management/IdentityManager.js, packages/caliper-fabric/test/identity-management/IdentityManager.js
=> improve message to help when file not found

docs/v0.4.2/Runtime_Configuration.md, docs/vNext/Runtime_Configuration.md
=> Remove countqueryasload option from docs

README.md, packages/caliper-cli/lib/launch/lib/launchWorker.js, packages/caliper-core/lib/worker/tx-observers/internal-tx-observer.js, packages/caliper-core/lib/worker/tx-observers/prometheus-push-tx-observer.js, packages/caliper-fabric/lib/connector-versions/v1/FabricGateway.js, packages/caliper-fabric/lib/connector-versions/v2/FabricGateway.js, packages/caliper-fabric/test/connector-versions/v1/FabricGateway.js, packages/caliper-fabric/test/connector-versions/v1/FabricNonGateway.js, packages/caliper-fabric/test/connector-versions/v2/FabricGateway.js, packages/caliper-gui-dashboard/public/index.html, packages/caliper-gui-dashboard/src/assets/css/paper-dashboard.css, packages/caliper-gui-dashboard/src/assets/css/paper-dashboard.min.css, packages/caliper-gui-dashboard/src/assets/scss/paper-dashboard.scss, packages/caliper-gui-dashboard/src/components/FixedPlugin/FixedPlugin.jsx, packages/caliper-gui-dashboard/src/components/Footer/Footer.jsx, packages/caliper-gui-dashboard/src/components/Navbars/Navbar.jsx, packages/caliper-gui-dashboard/src/components/Sidebar/Sidebar.jsx, packages/caliper-gui-dashboard/src/index.js, packages/caliper-gui-dashboard/src/layouts/Admin.jsx, packages/caliper-gui-dashboard/src/routes.js, packages/caliper-gui-dashboard/src/variables/charts.jsx, packages/caliper-publish/artifacts/verdaccio-config.yaml, packages/caliper-tests-integration/fabric_docker_local_tests/docker-compose.yaml
=> rename certain terms in code base

docs/vNext/Fabric_Configuration_New.md
This removes details from the network configuration docs of fabric (ie
how to create channels, install/instantiate chaincodes) as it shouldn't
be used.
The code will remain for now as the integration tests still require it.
=> [Docs] Remove fabric operations doc

packages/caliper-core/lib/worker/rate-control/recordRate.js, packages/caliper-core/test/worker/rate-control/mockRate.js, packages/caliper-core/test/worker/rate-control/recordRate.js
Addresses the record rate controller as it doesn't work and causes a
node stack overflow
closes #1131
=> fix RecordRate rate controller

packages/caliper-fabric/lib/connector-versions/peer-gateway/PeerGateway.js, packages/caliper-tests-integration/fabric_tests/docker-compose.yaml, packages/caliper-tests-integration/fabric_tests/phase2/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase3/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase4/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase5/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase6/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase7/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase7/ccp-org1.yaml, packages/caliper-tests-integration/fabric_tests/phase7/ccp-org2.yaml, packages/caliper-tests-integration/fabric_tests/phase7/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase7/queryByChannelNoTagetPeers.js, packages/caliper-tests-integration/fabric_tests/phase7/queryNoTargetPeers.js, packages/caliper-tests-integration/fabric_tests/phase8/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase8/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/run.sh
- add integration test for peer gateway connector
- updated docker compose to use fabric 2.4
=> Peer Gateway: Integration tests for the new Peer Gateway connnector ( + update docker compose to use 

packages/caliper-core/package.json
=> Fixed colors dependency to 1.4.0

docs/vNext/Architecture.md, docs/vNext/BenchmarkConfiguration.md, docs/vNext/ResourceAndTransactionMonitors.md, docs/vNext/tutorials_fabric_existing.md
Also renamed the file
closes #1213
=> [Doc] remove term Observer from monitors page

docs/v0.4.2/CONTRIBUTING.md, docs/vNext/CONTRIBUTING.md
Taken from hyperledger fabric :-)
=> [Doc] add inclusive guidelines for contributing

docs/v0.4.2/MonitorsAndObservers.md, docs/vNext/ResourceAndTransactionMonitors.md
=> [Doc] Clarify and fix monitor intervals

packages/caliper-tests-integration/fabric_tests/phase2/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase3/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase4/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase5/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase6/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase7/benchconfig.yaml
=> correct interval usage in fabric-tests

docs/v0.4.2/BenchmarkConfiguration.md, docs/v0.4.2/tutorials_fabric_existing.md, docs/vNext/BenchmarkConfiguration.md, docs/vNext/Fabric_Configuration_New.md, docs/vNext/tutorials_fabric_existing.md
Also remove references to `type: local` from benchmark files
=> [Doc] document the new peers property in fabric network config file

packages/caliper-tests-integration/fabric_docker_distributed_tests/config/generate.sh, packages/caliper-tests-integration/fabric_docker_distributed_tests/run-without-build.sh, packages/caliper-tests-integration/fabric_docker_local_tests/config/generate.sh, packages/caliper-tests-integration/fabric_tests/config/generate.sh, packages/caliper-tests-integration/generator_tests/fabric/config/generate.sh
=> Changed all 'bit.ly' links with a direct link

packages/caliper-cli/lib/lib/config.yaml
=> Explicitly bind grpc-js for fabric 2.4 connector

packages/caliper-fabric/lib/connector-versions/peer-gateway/PeerGateway.js, packages/caliper-fabric/test/connector-versions/peer-gateway/PeerGateway.js
=> Peer Gateway Connector Txs Error messsage: added output of err.details array

CHANGELOG.md, scripts/changelog.sh
=> [Release 0.5.0] Update Changelog

lerna.json, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
=> [Release 0.5.0] Publish official release

lerna.json, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
=> Bump to 0.5.1-unstable release

packages/caliper-cli/lib/lib/config.yaml
Updated fabric bindings: 
- fabric-network@2.2.12 -> 2.2.13
- @hyperledger/fabric-gateway@1.0.1 -> 1.1.0
Closes #1396 
=> Updated fabric bindings

.github/workflows/pr.yml
In this PR:
* The dci-lint workflow is added to the workflows executed on PR to the documentation branch.
Closes #1422
=> Add workflow for gh-pages branch

dev-docs/README.md, dev-docs/generate-figure.sh, dev-docs/proposals/0000-proposal-template.md, package.json
Draft PR showcasing the envisioned structure of the dev docs.
=> Add skeleton for development and proposal docs

Gemfile, docs/v0.3.2/Getting_Started.md, docs/v0.4.2/Getting_Started.md, docs/v0.5.0/Getting_Started.md, docs/vNext/Getting_Started.md
Fixes #1518
1.Open Documentation
2.Going to Getting Started
3.Click on the PSWG whitepaper link
The fix updates the PSWG white paper link in the Documentation to the correct URL: https://www.hyperledger.org/learn/publications/blockchain-performance-metrics.
=> Update PSWG whitepaper link in Documentation #1518

docs/v0.5.0/CONTRIBUTING.md, docs/vNext/CONTRIBUTING.md
Fixes #1529
- [ x]  A link to the issue/user story that the pull request relates to
1.
2.
3.
4.
=> Remove besu as an adapter

_config.yml, _includes/v0.3.2.html, _includes/v0.4.2.html, _includes/v0.5.0.html, _includes/v0.6.0.html, _includes/vNext.html, _layouts/v0.6.0.html, docs.json, docs/v0.6.0/Architecture.md, docs/v0.6.0/BenchmarkConfiguration.md, docs/v0.6.0/Benchmark_Generator.md, docs/v0.6.0/CONTRIBUTING.md, docs/v0.6.0/Caliper_FAQ.md, docs/v0.6.0/DeclarativeWorkloadModule.md, docs/v0.6.0/Ethereum_Configuration.md, docs/v0.6.0/Fabric_Configuration_New.md, docs/v0.6.0/Fabric_Tut.html, docs/v0.6.0/Getting_Started.md, docs/v0.6.0/Installing_Caliper.md, docs/v0.6.0/LICENSE.md, docs/v0.6.0/Logging_Control.md, docs/v0.6.0/Messengers.md, docs/v0.6.0/Rate_Controllers.md, docs/v0.6.0/ResourceAndTransactionMonitors.md, docs/v0.6.0/Runtime_Configuration.md, docs/v0.6.0/Workload_Module.md, docs/v0.6.0/Writing_Connectors.md, docs/v0.6.0/tutorials_fabric_existing.md
- move to 0.6.0 because fisco bcos was removed from this release
=> [Release 0.6.0] Documentation

docs/v0.6.0/ResourceAndTransactionMonitors.md, docs/vNext/ResourceAndTransactionMonitors.md
Fix [1437](https://github.com/hyperledger/caliper/issues/1437)  
#1437
=> Grafana correction in caliper documentation

CONTRIBUTING.md, package-lock.json, packages/caliper-core/lib/worker/tx-observers/prometheus-tx-observer.js, packages/caliper-core/package.json, packages/caliper-core/test/worker/tx-observers/prometheus-manager-tx-observer.js, packages/caliper-core/test/worker/tx-observers/prometheus-tx-observer.js, packages/caliper-tests-integration/besu_tests/phase1/networkconfig.json, packages/caliper-tests-integration/besu_tests/phase2/networkconfig.json, packages/caliper-tests-integration/besu_tests/phase3/networkconfig.json, packages/caliper-tests-integration/besu_tests/privatetxs/networkconfig.json, packages/caliper-tests-integration/ethereum_tests/networkconfig.json, packages/caliper-tests-integration/fabric_docker_distributed_tests/clean.sh, packages/caliper-tests-integration/fabric_docker_distributed_tests/run-with-build.sh, packages/caliper-tests-integration/fabric_docker_distributed_tests/run-without-build.sh, packages/caliper-tests-integration/fabric_docker_local_tests/clean.sh, packages/caliper-tests-integration/fabric_docker_local_tests/run-with-build.sh, packages/caliper-tests-integration/fabric_docker_local_tests/run-without-build.sh, packages/caliper-tests-integration/fabric_tests/phase1/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase6/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/run.sh, packages/caliper-tests-integration/generator_tests/fabric/run.sh
- [X ]  A link to the issue/user story that the pull request relates to
Fixes #1597  
N/A
- [ X] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [ X] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ X] [Discord history](https://discord.com/channels/905194001349627914/941417677778473031)
=> Bump test libraries to latest

docs/source/getting-started/contributing.md
=> fix packages err

docs/source/getting-started/installing-caliper.md
=> fix: doc reference

docs/source/tutorial/fabric.md
=> fix: tutorial section link

docs/source/getting-started/faq.md
fixes #1418
Signed-off-by: Dave Kelsey <dkel50@hotmail.com>
=> minor fix to faq around tps
