docs/Fabric Configuration.md, src/fabric/e2eUtils.js
Added configuration support for providing parameters for the chaincode's Init method during instantiation.
If not provided, the parameter array defaults to an empty array for backward compatibility reason.
Extended Fabric configuration documentation accordingly.
=> Added configuration support for chaincode Init parameters.

benchmark/simple/fabric.json, docs/Fabric Configuration.md, src/fabric/e2eUtils.js, src/fabric/util.js
Now Caliper search cryptographic materials in `cryptodir` with hard-coded path format. 
This patch allows users to define key and certification paths explicitly 
=> Support define key and certification path in fabric configuration

src/fabric/constant.js, src/fabric/e2eUtils.js
@haojun Here is the PR addressing issue #24 
Notable changes:
* Using async/await
* Added verified and error-related properties to the Tx status object
Regarding unverified failures:
Since it is not straightforward how to incorporate (if at all) the extra time needed to verify a Tx status through a query (and when to do that), I think the best option, for now, is to leave this to the callback module. It still has access to the configured context (except the event hubs) in the `end` callback, so if needed, verification can happen there.
=> Fixed Fabric Tx life-cycle handling

benchmark/composer/composer-micro/query-asset.js, src/contract/composer/vehicle-lifecycle-network/queries.qry
Composer 0.19.x now automatically creates indexes within CouchDB for any queries listed within the queries file of a business network that is deployed, in order to maximise the performance of queries.
This PR changes the example query test to use a query within the vehicle lifecycle network queries file so that the query tests being run are running at their maximum performance, as per the recommended best practise for Composer business networks. 
Signed-off-by: Nick Lincoln <nkl199@yahoo.co.uk>
=> Update Composer query test to use precompiled VL query

src/comm/client/local-client.js
Replace the wrong promise.all array in runDuration
=> Bug fix for runDuration

.eslintignore, benchmark/drm/main.js, benchmark/drm/publish.js, benchmark/drm/query.js, benchmark/simple/main.js, benchmark/simple/open.js, benchmark/simple/query.js
Regarding issue #48 , updated  benchmark/fabric and benchmark/drm config files to adhere to eslint rules.
Changes:
1. prefer `const` and `let ` over `var`.
2. prefer `'` over `"`.
3. Add missing semicolons.
4. JS-doc for main.js
=> Eslint compatible: Fabric and drm benchmark files

benchmark/simple/config-composite-rate.json, docs/RateControllers.md, src/comm/client/client-util.js, src/comm/client/local-client.js, src/comm/rate-control/compositeRate.js, src/comm/rate-control/noRate.js, src/comm/rate-control/rateControl.js
The aim of this PR is to pave the road for advanced workload modelling. Contributions include:
* Added `end` method to the rate controller proxy to signal the end of a round (in a backward compatible/optional way).
* Modified round execution workflow to call this `end` method.
* Added a composite rate controller implementation.
* Added a zero rate controller implementation.
* Extended the rate controller documentation.
* Added a sample configuration to demonstrate the usage of the new controllers.
* Propagate client index to _local_ clients.
=> Add rate controllers and related extensions, update docs

benchmark/composer/composer-samples/basic-sample-network.js, benchmark/composer/composer-samples/bond-network.js, benchmark/composer/composer-samples/digitalproperty-network.js, benchmark/composer/composer-samples/marbles-network.js, benchmark/composer/composer-samples/perishable-network.js, benchmark/composer/composer-samples/vehicle-lifecycle-network.js, benchmark/composer/composer-test-utils.js, benchmark/composer/config-composer.json, docs/Composer.md
Currently the Composer benchmark tests are in single client and single round mode only. This PR enables the benchmarks to be run in multi-client mode with multiple test rounds.
This was enabled by using the OS hostname and process id as a UUID within each test for the creation and manipulation of assets in each benchmark test.
Changes include:
- benchmarks edited to enable multi client/round
- config file changed so that travis test is in multi-client/round for composer
- docs updated to remove limitation on modes
PR checks made:
- eslint compliant
- each benchmark passes in multi-client/round mode
- travis build passes in multi-client/round mode
Signed-off-by: Nick Lincoln <nkl199@yahoo.co.uk>
=> enable multi-client and multi-round tests in Composer benchmarks

network/fabric/simplenetwork/docker-compose.yaml
In `network/fabric/simplenetwork/docker-compose.yaml` the container `couchdb` is defined but not used.
=> Delete Unused Container

network/fabric/simplenetwork/docker-compose.yaml
`network/fabric/simplenetwork/docker-compose.yaml` has many "copy & paste" lines. This patch deletes copied lines by using `extends` feature of Docker Compose.
=> Simplify docker-compose.yaml

docs/Composer.md
`benchmark/composer/runner.js` has been renamed to `main.js` at 3259d0a4f6bb2a5300c8c9986e472870481ef351.
=> Fix File Name in Composer Document

src/fabric/e2eUtils.js
The error handling part of a rejected Fabric Tx proposal referenced an undefined attribute of the response.
In case of rejected proposal, an explicit `Error` object is returned as result (see [this SDK code](https://github.com/hyperledger/fabric-sdk-node/blob/bc7d7db22e209f3c2477a0023ba0e8a0201cebe6/fabric-client/lib/client-utils.js#L103)).
@haojun can you review this quick-fix?
=> Fix rejected Fabric proposal handling

README.md, network/iroha/simplenetwork/docker-compose.yml, network/iroha/simplenetwork/node0/config.sample, network/iroha/simplenetwork/node1/config.sample, package.json, src/iroha/iroha.js
This PR introduces the new release of Iroha [v1.0 beta-3](https://github.com/hyperledger/iroha/releases/tag/v1.0.0_beta-3)
I actualized used containers in **docker-compose.yml**, simple benchmark code (we slightly changed our API) and node configs.
I removed grpc@1.10.1 from the main **package.json** because:
1. It sufficiently increases dependencies installing time by `npm install`. grpc _of this version_ compiles from sources, despite I have a very widespread system (Ubuntu 18.04, x86_64).
2. This grpc package conflicts with the version from **iroha-lib** package.
So I removed both dependencies and specify in README.md additional dependency iroha-lib@0.1.7 in Iroha's section and grpc@1.10.1 in Fabric's section. It's not the best solution, but I couldn't think of a better one
Also
We are …
=> Update Iroha to v1.0 beta-3

benchmark/simple/config-linear-rate.json, benchmark/simple/config-record-replay-rate.json, docs/RateControllers.md, src/comm/bench-flow.js, src/comm/rate-control/compositeRate.js, src/comm/rate-control/linearRate.js, src/comm/rate-control/rateControl.js, src/comm/rate-control/recordRate.js, src/comm/rate-control/replayRate.js
This PR adds three additional rate controller to Caliper:
1. Linear rate controller for gradually increasing the TPS rate
2. Record rate controller for recording the timings of a rate controller
3. Replay rate controller for replaying an arbitrary timing trace
For details, see the documentation.
Another minor change: the clients now receive the round index in the message, which is propagated to the controllers (and soon also for the callbacks, but that's an other PR).
=> Add linear, record and replay rate controllers

benchmark/marbles/config-fabric-go.json, benchmark/marbles/config-fabric-node.json, benchmark/marbles/fabric-go.json, benchmark/marbles/fabric-node.json, benchmark/marbles/init.js, benchmark/marbles/main.js, benchmark/marbles/query.js, benchmark/simple/config-node.json, benchmark/simple/config.json, benchmark/simple/fabric-node.json, benchmark/simple/fabric.json, docs/Fabric Configuration.md, src/comm/util.js, src/contract/fabric/marbles/go/marbles.go, src/contract/fabric/marbles/go/metadata/statedb/couchdb/indexes/indexOwner.json, src/contract/fabric/marbles/node/marbles.js, src/contract/fabric/marbles/node/metadata/statedb/couchdb/indexes/indexOwner.json, src/contract/fabric/marbles/node/package.json, src/contract/fabric/simple/go/simpletest.go, src/contract/fabric/simple/node/package.json, src/contract/fabric/simple/node/simpletest.js, src/fabric/e2eUtils.js
This PR addresses the following shortcomings:
* Proper support for Node.js chaincodes (CC)
* Support for CC metadata (CouchDB indices)
* Lack of Node.js CC examples
Contribution details:
* Correctly resolving CC path (relative or absolute) in case of Node CC
* Processing `metadataPath` attribute for CC install requests
* Added Node version of the `simple` benchmark (restructured the `src/contract/fabric/simple` folder a bit, changed configs accordingly)
* Added Node and Golang versions of the `marbles` CC from the `fabric-samples` repo (included a NOTE about this derivative work and a reference to the original, hopefully, this makes it license-compatible)
* Added `marbles` benchmark files for testing the corresponding CCs
* Fixed some bugs/typos in the `simple` Golang CC
* Updated …
=> Node CC and metadata support, node CC examples

src/comm/client/local-client.js
If an unhandled exception occurred in a client process, the main process printed the received error object as the following, obscuring the original error. Set an invalid callback name to reproduce it:
```
not ok 5 failed 'open' testing, Error: Client encountered error:[object Object] at ChildProcess.<anonymous>
```
Now it receives the `string` version of the error and prints it correctly:
```
not ok 5 failed 'open' testing, Error: Client encountered error:Error: Cannot find module '/home/klenik/projects/caliper-single-org/benchmark/simple/opennn.js' at ChildProcess.<anonymous>
```
=> Fix cross-process error message format

docs/Fabric Configuration.md
Added description in the Fabric network documentation about the `domain` attribute introduced by PR #126 
=> Add domain attribute to docs

benchmark/composer/composer-micro/query-asset.js, benchmark/drm/publish.js, benchmark/simple/fabric-node.json, benchmark/simple/fabric-remote.json, benchmark/simple/fabric.json, src/comm/bench-flow.js, src/comm/blockchain.js, src/comm/client/local-client.js, src/comm/transaction.js, src/comm/util.js, src/composer/composer.js, src/fabric/e2eUtils.js, src/fabric/fabric.js, src/iroha/iroha.js, src/sawtooth/sawtooth.js
1. Define a common TxStatus class and modify all adapters accordingly.
2. Reduce memory usage of local-client.js
=> define common TxStatus Class

src/comm/rate-control/pidRate.js
This is a minor problem I spotted well taking the pidRate controller for a spin.  Obviously the pidRate controller should return the Sleep promise rather than just leaving it, otherwise the test goes into a very tight loop and the rate isn't controlled at all.
Signed-off-by: Kevin O'Donnell <kevin@blockchaintp.com>
=> Minor fix: pidRate should return the Sleep promise not just create it. 

network/fabric/2-org-1-peer/composer-tls.json, network/fabric/2-org-1-peer/composer.json, network/fabric/2-org-2-peer/composer-tls.json, network/fabric/2-org-2-peer/composer.json, network/fabric/2-org-3-peer/composer-tls.json, network/fabric/2-org-3-peer/composer.json, network/fabric/3-org-1-peer/composer-tls.json, network/fabric/3-org-1-peer/composer.json, network/fabric/3-org-2-peer/composer-tls.json, network/fabric/3-org-2-peer/composer.json, network/fabric/3-org-3-peer/composer-tls.json, network/fabric/3-org-3-peer/composer.json, src/comm/bench-flow.js, src/comm/client/local-client.js, src/comm/rate-control/recordRate.js, src/comm/rate-control/replayRate.js, src/composer/composer_utils.js, src/fabric/create-channel.js, src/fabric/e2eUtils.js, src/fabric/join-channel.js, src/fabric/util.js, src/iroha/iroha.js
Related to Issue #95, this PR unifies the path resolution of different modules, by using [the following](https://github.com/hyperledger/caliper/blob/6cf2891736c60dfd5c0a3221f36b1841dc79318d/src/comm/util.js#L51) utility function.
Now every path in the config files can be set either as a relative path to the Caliper root directory or as an absolute path.
@nklincoln I successfully run a Composer sample benchmark, but could you review the Composer-related part just in case?
@haojun Can you tag someone from the Iroha contributors to review the Iroha-related part? Although those were (I hope) straightforward modifications.
=> Use common utility for path resolution

benchmark/composer/config-composer-dev.json, benchmark/simple/config-dev.json, benchmark/simple/fabric-dev.json, network/fabric/dev/README.md, network/fabric/dev/composer-tls.json, network/fabric/dev/composer.json, network/fabric/dev/docker-compose-tls.yaml, network/fabric/dev/docker-compose.yaml
Experimenting with benchmarks on a locally run multi-node network requires considerable resources. This PR adds a lightweight development network with an orderer node, a CA and a peer (and not using CouchDB). Corresponding config files are also added for the simple benchmark.
=> Added lightweight dev network

src/fabric/e2eUtils.js
Reject an error instead of undefined, otherwise it will log like this:
```
Failed to complete transaction [8c3b9...]:undefined
```
This got me confused.
Signed-off-by: modood <modood@qq.com>
=> Reject an error instead of undefined

benchmark/simple/main.js
Resolve absolute path of config file for fabric simple network
This should be valid:
```
$ node benchmark/simple/main.js -c /path/to/yourconfig.json -n /path/to/yournetwork.json
```
benchmark/simple/config.json:
```
{
"blockchain": {
"type": "fabric",
"config": "/path/to/yournetwork.json"
}
}
```
Signed-off-by: modood <modood@qq.com>
=> Resolve absolute path of config file for fabric simple network

docs/RateControllers.md, src/comm/rate-control/compositeRate.js, src/comm/rate-control/linearRate.js, src/comm/rate-control/noRate.js, src/comm/rate-control/recordRate.js, src/comm/rate-control/replayRate.js
Adjusted the composite rate controller to the new environment semantics as detailed by Issue #142.
The virtualization mechanism is not totally transparent now, but without passing more information to the rate controllers, this is the only way. Updated the docs accordingly.
@panyu4 since Nick has already fixed the PID controller, if this PR is accepted, then the issue can be closed.
=> Fixed composite rate controller logic and docs.

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
Add two templates:
- Issue
- PR
The two templates must be named accordingly and delivered into the project root directory, docs directory, or hidden `.github` dir .... I chose the first option!
=> add issue and PR templates

src/comm/monitor.js
in line 112 of file `src/comm/monitor.js`, it should check whether  `monitorTypes` is not defined, not the `m` which has been checked in line 107.
=> fix a bug of monitor.js

_includes/head.html, _includes/header.html
The PR adds:
* Google Analytics to every page of the site (through `_includes/head.html`)
* Privacy policy link to TLF privacy policy (through `_includes/header.html`)
* The GitHub and Privacy Policy links open in a new tab.
Modified site: https://aklenik.github.io/caliper/
=> Add Google Analytics and privacy policy

benchmark/simple/config-feedback-rate.json, benchmark/simple/config.json, benchmark/simple/open.js, src/comm/client/local-client.js, src/comm/rate-control/compositeRate.js, src/comm/rate-control/fixedFeedbackRate.js, src/comm/rate-control/rateControl.js, src/comm/rate-control/rateInterface.js, src/comm/rate-control/recordRate.js
The fixed feedback rate controller will send input transactions at a fixed interval, but when too many transactions are unfinished, it will sleep a period of time.
=> Add fixed feedback rate controller

benchmark/composer/composer-micro/query-asset.js, benchmark/composer/config-composer.json, benchmark/composer/main.js, network/fabric/2org1peer/composer-tls.json, network/fabric/2org1peer/composer.json, package.json, src/comm/bench-flow.js, src/comm/monitor/monitor-docker.js, src/comm/monitor/monitor-interface.js, src/comm/monitor/monitor-process.js, src/comm/monitor/monitor.js
Targets #140 
This PR enables hooking into the the disc r/w portion of dockerstats output for local tests, and updates the output tables in the console.
It was not needed to update the html file for test output as the template deals with the additional column.
I have noticed in the output that disc read remains at zero, but this corresponds to the actual dockerstats output during the test run
=> Enable display of disc r/w

src/comm/bench-flow.js, src/comm/client/client-util.js
When txNumber set in the configuration file can't be divisible by clients' number, the total transactions' quantity is less than txNumber which the user expected. 
Add the remainder transactions to one client.
=> fix the total send transactions according to configuration file

src/comm/bench-flow.js
This pr is trying to fix the the issue #273 , which appears the tps is much larger than the sending rate and equals to the success number.
=> fix the tps's bug

docs/Fabric_Ccp_Configuration.md
Added the example `npm run` scripts for v1.3 and v1.4.
Preview: https://aklenik.github.io/caliper/docs/Fabric_Ccp_Configuration.html#installing-the-required-dependencies
=> Update Fabric-CCP install instruction

package.json
When I did a composer test, The error "SyntaxError: Unexpected end of JSON input" occured. The error  is  because I'm using composer 0.19 with a fabric 1.2 environment and they are mismatch. So we need to fix this.
=> Fix the versions of composer and fabric mismatch

network/sawtooth/simplenetwork/sawtooth-simple.yaml
The Docker build script assumes that the Caliper repo is cloned into a `caliper` folder. But actually, the last `../caliper/` directory change is unnecessary. 
```
git clone https://github.com/hyperledger/caliper.git caliper-fork
docker rmi simple-tp-python
npm i
npm run sawtooth-deps
npm run bench -- -c benchmark/simple/config-sawtooth.yaml -n network/sawtooth/simplenetwork/sawtooth.json
```
The path reference is simplified in the build script, thus completely avoiding the Caliper directory name.
Repeat the above steps to reproduce.
=> Fix project path for Sawtooth example build

src/adapters/fabric/constant.js
When multi-users in one host use caliper to test, the directory '/tmp/hfc/ ' permission is denied for the sake of using the same directory.
=> Using user tmp dir

benchmark/simple/config.yaml, src/comm/bench-flow.js, src/comm/report.js, src/comm/template/report.html
Suggested fix for #382
Following the generation of some Caliper reports, I noticed that the report structure could be enhanced. I have changed the template and associated report code to follow the config file more closely and make the report more readable by:
- Group test rounds under each test label, with each round starting at zero for each label.
- Link to test labels instead of test rounds from the metadata side navigation (this is a more meaningful link)
- Enable the provision of a description for each test label that is taken from the config file.
I have attached a file that is generated by the code.
[report-20190320T153655.html.zip](https://github.com/hyperledger/caliper/files/2991612/report-20190320T153655.html.zip)
=> Modify report template to list based on test label

packages/caliper-core/lib/blockchain.js, packages/caliper-core/lib/caliper-flow.js, packages/caliper-core/lib/rate-control/fixedRate.js
When the  transactions are not sent evenly eg. sending several transactions with one workload, current TPS may give some strange throughtput since in some situations the time used for transactions is not accurately computed. 
#226 
1. record the maximum final time of all successful and failed transactions;
2. modify the computation of successful transactions time to the all transactions used time 
1. start Caliper normally with 'open' test module and 'txnPerBatch' set larger than TPS ;
2. open another terminal and stop the running blockchain network.
=> Fix TPS computation for batch mode

packages/caliper-application/benchmark/smallbank/query.js, packages/caliper-application/benchmark/smallbank/smallbankOperations.js
Signed-off-by: quangtdn <nmquang229@yahoo.com.vn>
Please refer to #395  .
In the benchmarking methods smallbankOperations.js and query.js, for fabric-ccp type the test should convert transactions' arguments into Strings before sending the transactions.
=> [updated] Fix conflicts between smallbank benchmark and fabric-ccp configuration

packages/caliper-core/lib/config/Config.js
The [config doc states](https://hyperledger.github.io/caliper/docs/Runtime_Configuration.html#command-line-arguments) that command line argument and environment variable names are "normalized" to lower-case letters separated with dashes to be more robust and convenient to set.
Currently, this transformation is performed for every setting, which might not be desirable.
Only the setting names starting with `caliper-` (after normalization) are actually changed.
=> Fixed setting key renaming

docs/1_Getting_Started.md
Resolves #445
- updates Node dependancies, with an explicit warning on not going too high
- updates bootstrap process with a warning not to use sudo
identical changes have been made to the repo readme within PR #468 
=> Update dependancies and bootstrap process

packages/caliper-core/lib/caliper-flow.js, packages/caliper-core/lib/client/client-orchestrator.js, packages/caliper-core/lib/report/report-builder.js, packages/caliper-core/lib/report/report.js, packages/caliper-core/lib/test/defaultTest.js, packages/caliper-core/lib/utils/caliper-utils.js
This PR removes the report generation and default test from `caliper-flow`. This reduces the flow file size considerably.
The following is introduced:
- a report class builds an internal report using a report builder
- a `DefaultTest` class is used to encapsulate the test run process
This should enable the components to be maintained in a more isolated fashion, and lend itself to modularization of these components. 
=> remove report build and default test from caliper-flow

packages/caliper-core/lib/monitor/monitor-docker.js
When I try to use a remote docker and passing the link of it into the config file, like:
http://127.0.0.34:2375/all
Caliper is not able to fetch the stats data of all the docker containers.
I guess that a similar problem is present on the "else" of the same branch. line: 121 (NOT FIXED)
1. To recreate the bug just start hyperledger caliper passing the endpoint to the remote docker.
> monitor:
>   type:
>   - docker
>   docker:
>     name: 
>         **- http://127.0.0.34:2375/all**
>   interval: 1;
The result of the execution, without the fix, will be to do not be able to fetch the containers stats.
In any case, the value inside filterName.remote[h].containers cannot exclude the '/'.
The value is coming from line: 49, the function url.parse is cutting the different parts of the url and …
=> Fixed expected parameter

packages/caliper-burrow/lib/burrowClientFactory.js, packages/caliper-composer/lib/composerClientFactory.js, packages/caliper-core/lib/client/client-util.js, packages/caliper-core/lib/config/config-util.js, packages/caliper-core/lib/config/default.yaml, packages/caliper-fabric-ccp/lib/fabric.js, packages/caliper-fabric-ccp/lib/fabricClientFactory.js, packages/caliper-fabric-ccp/lib/fabricClientWorker.js, packages/caliper-fabric-ccp/lib/fabricNetwork.js, packages/caliper-fabric/lib/fabricClientFactory.js, packages/caliper-iroha/lib/irohaClientFactory.js, packages/caliper-sawtooth/lib/sawtoothClientFactory.js, packages/caliper-tests-integration/scripts/run-integration-tests.sh
This PR extends the fabric-ccp adaptor to enable a user to specify the use of a Fabric Gateway based transaction by the addition of a `use-gateway: true` flag on the benchmark configuration file.
Changes:
- check/set of a `usegateway` flag within Fabric Network
- conditioning on fabric client version>=1.4.0 to use the new flag
- construction of required items (wallets and gateway contracts) during init/getContext phases
- fork in main submit/evaluate pathway to test with either the Gateway contract or the standard caliper client
- modification of integration test to use the alternative route (both client routes are tested)
Code flow:
- during the creation of clients, identities are conditionally added to an in-memory wallet
- during …
=> Enable user to specify a client gateway test

packages/caliper-fabric-ccp/package.json, packages/caliper-fabric/package.json, packages/caliper-tests-integration/package.json
Vulnerability scan showed some version issues within verdaccio, and the warning on a fs-extra hoist mis-match during bootstrap is getting frustrating ... this PR resolves both.
=> update versions to remove verdaccio vulnerability and bootstrap warning

packages/caliper-samples/network/fabric-v1.0/2org1peercouchdb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.0/2org1peergoleveldb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.1/2org1peercouchdb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.1/2org1peergoleveldb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.2/2org1peercouchdb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.2/2org1peergoleveldb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.3/2org1peercouchdb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.3/2org1peergoleveldb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.4.1/2org1peercouchdb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.4.1/3org2peercouchdb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.4.1/3org2peergoleveldb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.4/2org1peercouchdb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.4/2org1peergoleveldb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.4/3org2peercouchdb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.4/3org2peergoleveldb/docker-compose.yaml, packages/caliper-samples/network/fabric-v1.4/kafka/docker-compose.yaml
Fabric yaml files modified to specify CORE_CHAINCODE_EXECUTETIMEOUT with a large number to enable a larger timeout before failing the transaction.
=> Modify timeout setting for Fabric chaincode execute

packages/caliper-composer/lib/composer.js
At the moment failing composer transactions are not identified, which is problematic when trying to set up a Composer test.
This PR adds logging of any error messages coming back from the failed transaction to help assist in debugging
=> Add composer transaction fail error

.travis.yml, .travis/avoid_verdaccio.sh, packages/caliper-tests-integration/package.json, packages/caliper-tests-integration/scripts/run-tests-direct.sh
Current builds are failing due to what appears to be a significant resource availability drop that is preventing the use of the verdaccio test process, which requires significant resource utilisation during the hosting of the proxy npm server.
This PR circumvents the verdaccio process as a temporary measure to get the build pipeline working again. The new route tests the CLI `caliper.js` directly, rather than installing it as a CLI package
=> avoid verdaccio use during build tests

.gitignore
When moved from master to gh-pages branch, files (e.g. .pm2, coverage files) that should have been ignored were appearing.
Modified the gitignore file to rectify this.
=> Modify gitignore file

packages/caliper-fabric/lib/fabric.js
The gateway created in fabric.js will pick up on the default config unless it is overridden as a gateway config as an event handler option. 
This should be done on gateway creation, and can neatly pick up on the default test parameter
=> make gateway timeout configurable with configDefaultTimeout

packages/caliper-core/lib/caliper-flow.js, packages/caliper-core/lib/config/config-util.js, packages/caliper-core/lib/config/default.yaml, packages/caliper-core/lib/utils/caliper-utils.js, packages/caliper-fabric/lib/fabric.js, packages/caliper-samples/benchmark/marbles/config.yaml
Related to #535 and enables conditional caliper-flow actions of:
- run start scripts
- run init phase
- run install smart contract phase
- run test phase
- run end script phase
All the above controlled via a config item passed at the command line level
=> Condition Caliper flow

packages/caliper-fabric/lib/fabric.js, packages/caliper-fabric/lib/fabricNetwork.js
This change permits an exported wallet to be used for the configuration/testing of a Fabric network and simplifies the interaction with an already deployed network.
Changes include:
- enable a single wallet path to be specified in network file
- modify validation to set if wallet being used, and reduce client spec requirements in the case a wallet is being used
- if file wallet is present, enable the extraction of identity and associated crypto material for configuring admin/client profiles used in the test phase
Related to #553
=> Enable single wallet to be specified and used as client crypto store

docs/1_Getting_Started.md, docs/Fabric_Configuration.md, docs/Installing_Caliper.md
Corresponding docs for #562 
Additional modifications:
* Consolidated the Getting started page. Now every install and run how-to is in one page.
Preview: https://aklenik.github.io/caliper/docs/Installing_Caliper.html
=> Add documentation for installing Caliper

packages/caliper-tests-integration/scripts/buildDockerImage.js
When building the Docker image from the public NPM packages, the "empty" registry argument was passed incorrectly, resulting in an erroneous npm call.
=> Fix Docker build script for public NPM repo

packages/caliper-core/lib/blockchain-interface.js, packages/caliper-core/lib/blockchain.js
This PR adds the companion method of `invokeSmartContract` to expose the ability to `querySmartContract` from the blockchain object directly, thereby raising the ability to perform the call beyond a Fabric level interaction. 
This will give Caliper testing the ability to:
- explicitly perform a query using a deployed smart contract
- explicitly perform a query by going direct to the ledger if the underlying DLT engine permits it
=> add a query smart contract method

docs/vNext/Architecture.md, docs/vNext/CONTRIBUTING.md, docs/vNext/Getting_Started.md, docs/vNext/Logging_Control.md, docs/vNext/MonitorsAndObservers.md, docs/vNext/Rate_Controllers.md, docs/vNext/Runtime_Configuration.md, docs/vNext/Writing_Adapters.md, docs/vNext/Writing_Benchmarks.md, docs/vNext/architecture_CH.md
Docs to accompany the Prometheus PR #588 
=> Add docs for Prometheus

packages/caliper-core/lib/config/Config.js, packages/caliper-core/lib/config/config-util.js, packages/caliper-core/lib/config/default.yaml, packages/caliper-core/lib/utils/caliper-utils.js, packages/caliper-fabric/lib/configValidator.js, packages/caliper-fabric/lib/fabric.js, packages/caliper-fabric/lib/fabricNetwork.js, packages/caliper-fabric/package.json, packages/caliper-fabric/test/configValidator.js, packages/caliper-samples/network/fabric-v1.4/2org1peercouchdb/fabric-node.yaml
Resolves part of issue #467 
(Also moves the config runtime key names, so the Config.js module can use them without a circular dep issue.)
The validation part of the `fabricNetwork.js` module was extracted into `configValidator.js`, which uses the joi package to define and validate object schemas declaratively. This makes it easy to adapt the validation rule for future/changed schemas.
Unit tests cover the entire schema, property-by-property (since the schema is declarative, code coverage is not representative). The expected error/joi messages are checked to ensure that the test targets the intended property error (and isn't masked by an other error).
Even though this is just an under-the-hood change, the Fabric adapter docs is also …
=> Add declarative validation for Fabric network config files

packages/caliper-core/lib/caliper-flow.js, packages/caliper-core/lib/config/Config.js, packages/caliper-core/lib/config/default.yaml, packages/caliper-core/lib/report/report-builder.js, packages/caliper-core/lib/report/report.js, packages/caliper-core/lib/utils/caliper-utils.js
Resolves #597 
The PR makes the reporting path configurable through the usual runtime config mechanism. Plus exposes the file access settings, which can come in handy when the container executes Caliper as root.
=> Make report file path configurable

packages/caliper-core/.gitignore, packages/caliper-core/lib/config/Config.js, packages/caliper-core/lib/config/config-util.js, packages/caliper-core/lib/config/default.yaml, packages/caliper-core/lib/utils/caliper-utils.js, packages/caliper-core/lib/utils/logging-util.js, packages/caliper-core/package.json, packages/caliper-sawtooth/.gitignore
Resolves #581 
The PR includes:
1. Changing to winston 3.X, to utilize the new formats feature
2. Restructure the logging section of the runtime settings
1. Keep implementation-specific options separated for target transports
2. Make targets easy to disable/enable
3. Make logging style easily configurable
4. Provide a message structure template
3. Related docs in other PR
=> Enhance logging subsystem with flexible customization

packages/caliper-core/lib/monitor/monitor-orchestrator.js
The Prometheus edit removed the ability to have 'none' as an option for monitors ... this brings back the option 👍 
The monitors/observer docs already include 'none' as an option .... so no docs change needed
=> enable no monitors to be specified in benchmark config

.gitignore, packages/caliper-fabric/lib/fabric.js
Fixes the mutual TLS configuration bug for Fabric gateway mode.
=> Fix mutual TLS for Fabric gateway mode

packages/caliper-core/lib/monitor/monitor-orchestrator.js, packages/caliper-core/lib/monitor/monitor-prometheus.js, packages/caliper-core/test/client/client-orchestrator.js, packages/caliper-core/test/monitor/monitor-prometheus.js, packages/caliper-core/test/prometheus/prometheus-query-helper.js
The Prometheus enablement PR managed to sneak in a `.only` in a mocha test, which essentially killed all the existing unit tests .... this fixes that!
=> remove .only on mocha  test

packages/caliper-core/lib/config/Config.js, packages/caliper-core/lib/config/default.yaml, packages/caliper-core/lib/utils/log-formats.js, packages/caliper-core/lib/utils/logging-util.js, packages/caliper-core/package.json, packages/caliper-samples/network/fabric-v1.4.1/2org1peercouchdb/fabric-node.yaml, packages/caliper-tests-integration/scripts/run-tests.sh
The new logging formats introduced by #598 were not flexible enough to create consistent all-line coloring, for example (and also had issues with JSON formatting). This PR fixes that by using a more flexible color and attribute formatter, and a strictly ordered formatting pipeline.
=> Improve logging style flexibility

packages/caliper-tests-integration/.dockerignore, packages/caliper-tests-integration/fabric_tests/.gitignore, packages/caliper-tests-integration/fabric_tests/caliper.yaml, packages/caliper-tests-integration/fabric_tests/config/.gitignore, packages/caliper-tests-integration/fabric_tests/config/configtx.yaml, packages/caliper-tests-integration/fabric_tests/config/crypto-config.yaml, packages/caliper-tests-integration/fabric_tests/config/generate.sh, packages/caliper-tests-integration/fabric_tests/docker-compose.yaml, packages/caliper-tests-integration/fabric_tests/init.js, packages/caliper-tests-integration/fabric_tests/phase1/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase1/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase2/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase2/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase3/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase3/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase3/src/marbles/go/marbles.go, packages/caliper-tests-integration/fabric_tests/phase3/src/marbles/go/metadata/statedb/couchdb/indexes/indexOwner.json, packages/caliper-tests-integration/fabric_tests/phase3/src/marbles/node/marbles.js, packages/caliper-tests-integration/fabric_tests/phase3/src/marbles/node/metadata/statedb/couchdb/indexes/indexOwner.json, packages/caliper-tests-integration/fabric_tests/phase3/src/marbles/node/package.json, packages/caliper-tests-integration/fabric_tests/phase4/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase4/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase5/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase5/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/prometheus/prometheus-fabric.yml, packages/caliper-tests-integration/fabric_tests/query.js, packages/caliper-tests-integration/fabric_tests/run.sh, packages/caliper-tests-integration/package.json, packages/caliper-tests-integration/scripts/run-tests.sh
Adds a multi-phase Fabric test for CI, that is independent of the samples (because of #569)
SUT details (`packages/caliper-tests-integration/fabric-tests` dir):
* 2 Orgs, 1-1 peer, 1-1 CA, 2 Raft orderers, mutual TLS
* 2 channels, Marbles golang CC (with rich query) in both channel
* Benchmark configs:
* 3 rounds (init, init, query)
* With 3 different rate controllers
* Different observer and monitor combination for each phases
* Dedicated network config for all phases, stripped to the required minimum
* Phases
1. Only start the network
2. Only initialize the network
3. Only deploy the contracts (channels already created)
4. The previous phase again to check the correct detection of already deployed contracts
5. Only performing the testing …
=> Add multi-phase Fabric CI test

docs/vLatest/Installing_Caliper.md, docs/vNext/Installing_Caliper.md
Getting started docs refers to path that existed in the local caliper repository, but we refer users to the caliper-benchmarks repository that has a different set of available networks ... this updates a command path to match that available
=> Match network path to that on repository

packages/caliper-ethereum/lib/ethereum.js, packages/caliper-samples/network/besu/1node-clique/ethereum.json, packages/caliper-tests-integration/besu_tests/networkconfig.json
* Estimating gas is now an explicit opt in, and secondary to explicit
gas values.
* Nonces are only added if caliper signs the transactions
* Update explicit gas in simple transfer queries
Signed-off-by: Danno Ferrin \<danno.ferrin@gmail.com\>
=> Update gas and nonce management for Ethereum

packages/caliper-core/test/worker/rate-control/linearRate.js
Test for the LinearRate controller
=> Linear rate controller

packages/caliper-ethereum/package.json
Minor version bump in web3 has broken everything :(
This PR pins the web3 dependancy in the ethereum adaptor to a set (working) level
=> Build Fix- modify web3 level

packages/caliper-fisco-bcos/lib/common.js, packages/caliper-fisco-bcos/lib/fiscoBcos.js, packages/caliper-fisco-bcos/lib/fiscoBcosApi.js, packages/caliper-fisco-bcos/lib/generateRawTransactions.js, packages/caliper-fisco-bcos/lib/installSmartContract.js, packages/caliper-fisco-bcos/lib/invokeSmartContract.js, packages/caliper-fisco-bcos/lib/sendRawTransactions.js, packages/caliper-fisco-bcos/package.json
FISCO adaptor includes chalk, which is not required as the Logger can provide colour options. This PR removes the chalk dependancy
=> remove chalk usage in fisco adaptor

docs/vNext/Ethereum_Configuration.md
Document the `fromAddressSeed` option and priority of configurations.
Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>
1.
2.
3.
4.
=> Document Ethereum `fromAddressSeed` option

packages/caliper-ethereum/lib/ethereum.js
Javascript "Truthy" of zero keeps us from going down the fork where nonces
are set.  Use typeof !== 'undefined' instead.
Signed-off-by: Danno Ferrin \<danno.ferrin@gmail.com\>
1.
2.
3.
4.
=> Fix ethereum adapter zero nonce issue

packages/caliper-core/lib/common/config/Config.js, packages/caliper-core/lib/common/config/default.yaml, packages/caliper-core/lib/master/charts/chart-builder.js, packages/caliper-core/lib/master/monitor/monitor-docker.js, packages/caliper-core/lib/master/monitor/monitor-orchestrator.js, packages/caliper-core/lib/master/monitor/monitor-process.js, packages/caliper-core/lib/master/monitor/monitor-prometheus.js, packages/caliper-core/lib/master/monitor/monitor-utilities.js, packages/caliper-core/lib/master/report/report-builder.js, packages/caliper-core/lib/master/report/report.js, packages/caliper-core/lib/master/report/template/report.html, packages/caliper-core/lib/master/test-runners/round-orchestrator.js, packages/caliper-core/package.json, packages/caliper-core/test/master/charts/chart-builder.js, packages/caliper-core/test/master/monitor/monitor-utilities.js, packages/caliper-tests-integration/fabric_tests/phase2/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase3/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase4/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase5/benchconfig.yaml
This PR provides enhanced report outputs for a user
Breaking changes:
- monitor configuration for docker and process monitors.
- docker monitor `name` filter changed to `container`, to better reflect what it is filtering
- process monitor now has the array of process to monitor under a `processes` block
Other Changes:
- Main report styling change
- Conversion of report tables to be normalised to a single metric. Each column is normalised to the largest value, to a user configurable precision. 
- Addition of charts to output report (user opt-in, for each monitor)
=> Enable charts to be included in output report

docs/vNext/Benchmark_Generator.md
Update benchmark generator to include documentation on the chaincode argument prompts and using the generator non-interactively using command line options
=> Update generator docs to include chaindcode argument prompt

packages/caliper-gui-dashboard/.gitignore, packages/caliper-gui-dashboard/README.md, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-dashboard/public/index.html, packages/caliper-gui-server/README.md, packages/caliper-gui-server/app.js, packages/caliper-gui-server/package.json
Currently it is not possible to stand up the GUI, this PR:
- pins npm requirement to fixed version
- fixes a typo
- adds the required html file and modifies the gitignore file so it is tracked
- modifies readme files to match required commands for standing up the GUI
=> enable gui

packages/caliper-core/lib/worker/rate-control/fixedBacklog.js, packages/caliper-core/package.json, packages/caliper-core/test/worker/rate-control/fixedBacklog.js
Allow user to specify a startingTps and change debug message.
Closes #701
=> Fixed backlog controller enhancement

docs/vNext/MonitorsAndObservers.md
There was an error in the docs for docker charting, with the metrics being show as an array, when it needed to be an object, like all the other specs
=> Fix incorrect docker charting spec

.travis.yml, .travis/benchmark-integration-test-direct.sh, .travis/checks-and-unit-tests.sh, .travis/docker-publish.sh, .travis/npm-publish.sh, package.json
* The CI jobs are conditional based on whether there are any decrypted vars (should speed up the build a bit)
* The NPM packages are tagged `unstable` or `latest` based on the version string in the root package.json
* Lerna should avoid any git magic now which previously broke the build
=> Made the CI jobs conditional and fixed lerna publish

packages/caliper-fabric/lib/adaptor-versions/v2/fabric-gateway-v2.js
Fabric SDK 2.0.0-beta has breaking changes in the way wallets are interacted with. This updates the file wallet interaction to work with the new SDK:
- `wallet.exists()` no longer exists, the `wallet.get()` will return undefined if not present
- `wallet.export()` has been replaced with `wallet.get()`
- returned information structure has changed
=> update wallet interaction with breaking sdk changes

packages/caliper-core/lib/master/monitors/monitor-docker.js, packages/caliper-core/lib/master/monitors/monitor-process.js
Additional columns were appearing in report file- this was a result of non-matching column names :
- CPU% (max) and CPU%(max)
- CPU% (av) and CPU%(av)
Fix is to remove the whitespace so that they all match - we also do not need to normalize on % values (🤦‍♂ )
Pre-fix
post-fix
corresponding report
=> remove whitespace between CPU% and (val)

packages/caliper-core/lib/common/prometheus/prometheus-query-helper.js, packages/caliper-core/test/common/prometheus/prometheus-query-helper.js
turns out that enabling a sum to be returned from a query result is *really* handy!
This PR adds the ability to request a sum of returned results, and adds a test for it too.
=> enable statistic summation on prometheus queries

docs/vNext/MonitorsAndObservers.md
Companion docs change for #720
=> add prometheus sum to docs

packages/caliper-core/index.js, packages/caliper-core/lib/master/caliper-engine.js, packages/caliper-core/lib/master/orchestrators/monitor-orchestrator.js, packages/caliper-core/lib/master/orchestrators/round-orchestrator.js
Code tidy: file relocation
The round orchestrator is an orchestrator, and so lives quite neatly under the orchestrators folder, alongside the worker-orchestrator.
The same is true for the monitor-orchestrator.
The GUI attempts to import numerous items (including orchestrators) that are not currently exported, so this PR also exports the items (namely the orchestrators) that it is trying (or might want to try) to import and use.
=> move orchestrators under orchestrator folder

packages/caliper-fabric/lib/configValidator.js, packages/caliper-fabric/test/configValidator.js
The current validator is a little too strict in certain places, this PR makes some minor modifications (with matching changes in the tests):
- force a semantic-versioning check on the network file (instead of having to be 1.0)
- channel stanza does not need peer list if in discovery mode
- registrar is not an absolute requirement if running in a test only mode
=> fix config validator for permitted properties

packages/caliper-ethereum/package.json, packages/caliper-fabric/lib/adaptor-versions/v1/fabric-v1.js, packages/caliper-fabric/lib/adaptor-versions/v2/fabric-v2.js, packages/caliper-fabric/lib/fabricNetwork.js, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json
closes #690 
- New method with the `FabricNetwork` class to retrieve and orderer object from the  passed network configuration
- Build orderer objects to use instead of an array of orderer names
=> Build orderer objects instead of names in cache

packages/caliper-cli/lib/bind/config.yaml
Modifies CLI binding configuration file to:
- add released 1.4.5 SDK
- make the added 1.4.5 the latest
=> add new 1.4.5 release to supported fabric sdks in cli

docs/vNext/Installing_Caliper.md
* The `--registry` argument was missing, defaulting to the NPM registry.
* Also delegated the global CLI install gotchas to the official NPM guide.
=> Fixed example for local Verdaccio publishing

docs/vNext/Installing_Caliper.md
=> Update docs for new CLI commands

packages/caliper-core/lib/worker/rate-control/compositeRate.js, packages/caliper-core/lib/worker/rate-control/recordRate.js, packages/caliper-core/lib/worker/rate-control/replayRate.js
The passing of the round index has changed somewhere, so some rate controllers read undefined.
Closes #686
=> Fix round index handling in rate controllers

packages/caliper-fabric/lib/adaptor-versions/v1/fabric-v1.js, packages/caliper-fabric/lib/adaptor-versions/v2/fabric-v2.js
=> Fix Fabric orderer error handling

packages/caliper-fabric/lib/adaptor-versions/v1/fabric-v1.js, packages/caliper-fabric/lib/adaptor-versions/v2/fabric-v2.js
Closes #702 
(Although the issue is not directly related to this PR, it uncovers a bug)
=> Fix Fabric channel init

packages/caliper-core/lib/common/utils/benchmark-validator.js
It is perfectly valid to use a prometheus based monitor and 'none' option for the observer ... this PR enables this specification by correctly conditioning the validation check
=> be more explicit in monitor/observer check

packages/caliper-fabric/lib/adaptor-versions/v2/fabric-v2.js
Fix bug in code for v2 fabric adaptor within the orderer name check.  Bug does not exist in the V1 counterpart.
This does hint towards some anti-practice going on where where have too much code replication.
=> fix orderer name check in fabric v2

packages/caliper-core/package.json
Closes #764 
Seems we can bump the consumed version of dockerode to 3.1.0 without any additional updates as there are no breaking changes in the functions that we are using.
Ran locally and witnessed disc i/o results 👌
=> update dockerode to 3.1.0

packages/caliper-ethereum/lib/ethereum.js
Web3 has recently added features that lazily fetches missing information
when signing and sending transactions. In our case, this was the
chainId, and the current gasPrice. Because transactions are submitted
asynchronously, these additional requests would sometimes cause
transactions to be submitted out of order. Even if this probelm were
mitigated, these additional requests added spurious latency spikes to
some transactions, negatively impacting the test results.
This partially addresses #776  by eliminating request reordering issues
for stable websocket connections. This change does not however address
transaction reordering for HTTP connections, or for websocket
connections that require reconnects. It also does not solve the
"christmas tree light" issue w.r.t. nonce errors.
=> ethereum: prevent unnecessary additional requests

packages/caliper-core/lib/worker/client/message-handler.js, packages/caliper-ethereum/lib/ethereum.js, packages/caliper-sawtooth/lib/sawtooth.js, packages/caliper-tests-integration/besu_tests/open.js, packages/caliper-tests-integration/besu_tests/query.js, packages/caliper-tests-integration/besu_tests/transfer.js, packages/caliper-tests-integration/ethereum_tests/open.js, packages/caliper-tests-integration/ethereum_tests/query.js, packages/caliper-tests-integration/ethereum_tests/transfer.js
* The `bcType` => `getType()` fix is applied to the Ethereum and Besu CI workload modules.
* The TX and unexpected errors are separated in the Ethereum adapter. The latter now halt and fails the benchmark.
* Worker-side errors are now reported with a stack trace in the logs.
* Sawtooth adapter bug fixed, referenced non-existing instance variable.
=> Fix CI workloads and enhance error handling

packages/caliper-cli/lib/lib/config.yaml, packages/caliper-fabric/.eslintrc.yml, packages/caliper-fabric/lib/adapterFactory.js, packages/caliper-fabric/lib/adaptor-versions/v1/fabric-gateway-v1.js, packages/caliper-fabric/lib/adaptor-versions/v1/fabric-v1.js, packages/caliper-fabric/lib/adaptor-versions/v2/fabric-gateway-v2.js, packages/caliper-fabric/lib/adaptor-versions/v2/fabric-v2.js, packages/caliper-fabric/lib/adaptor-versions/v2/registrarHelper.js, packages/caliper-fabric/lib/configValidator.js, packages/caliper-fabric/lib/fabric.js, packages/caliper-fabric/lib/fabricNetwork.js, packages/caliper-fabric/package.json, packages/caliper-fabric/test/configValidator.js, packages/caliper-fisco-bcos/.eslintrc.yml
A few changes here:
- Bindings
- Added a bind point with a current V2 snapshots
- ESLint
- Added `prefer const` to the eslint rule for fabric
- Fabric V2
- Will throw if not using `gateway` mode (can work on non-gateway in background and enable it)
- Updated fabric gateway adaptor to be compatible with latest working snaphot
- No admin actions (warn if used)
- Account for breaking changes in APIs
- Added a registrar helper to perform any enrol actions for users to with no credentials
- Enabled `countQueryAsLoad`
- Fabric V1 Gateway
- Updated the adaptor to mirror the V2 adaptor and accept transient data
- Enabled `countQueryAsLoad`
=> Enable fabric adaptor with most recent snapshot of v2 fabric sdk

.travis/benchmark-integration-test-direct.sh, packages/caliper-tests-integration/besu_tests/run.sh, packages/caliper-tests-integration/ethereum_tests/run.sh, packages/caliper-tests-integration/fabric_tests/run.sh, packages/caliper-tests-integration/fisco-bcos_tests/run.sh, packages/caliper-tests-integration/sawtooth_tests/run.sh
An explicit binding step is added to the Fabric CI test instead of using the latest dev deps.
* This opens up the possibility for a fabric-v2 CI test.
* The other CI adapter tests can introduce the same approach if needed to deviate from the latest dev deps.
=> Add binding to CI tests

packages/caliper-cli/lib/lib/config.yaml
Update besu to support 1.3 and 1.4 via semver.  Keep 1.3.2 in place to
support legacy configurations.
Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>
=> Update Besu Support

packages/caliper-cli/lib/lib/config.yaml, packages/caliper-fabric/lib/adaptor-versions/v2/fabric-gateway-v2.js
Make use of the most recent ability to gain direct access to the txID from the transaction object.
- updated v2 binding
- removed uuid require
- txID is populated on the TxStatus object after the txn has been completed
- cried when I noticed that the TxStatus object uses capitalised method names 😢
=> update v2 gateway

packages/caliper-publish/caliper.Dockerfile
* The core module is installed explicitly, so it's placed at the root of the global node_modules folder. The other core deps are deduped to this.
* NODE_PATH is set to the global node_modules folder, so external modules (like the workload module) can require it without explicitly installing it as its own dependency (and possibly breaking singleton patterns, since that'll be a different module).
=> Improve Dockerfile for global modules

packages/caliper-core/lib/common/config/Config.js, packages/caliper-core/lib/common/config/default.yaml, packages/caliper-core/lib/common/utils/circular-array.js, packages/caliper-core/lib/worker/client/caliper-local-client.js
Closes #729 
- uses a circular array with a maximum size that will act to overwrite previous entries once the maxLength is reached
- maxLength made configurable within the config (default 100) under the worker, since the worker is issuing the txns
Open to thoughts on the default maxTxn size, I picked 100 as an initial number, but perhaps should be higher?
=> Add a circular array of txPromises

packages/caliper-core/lib/master/report/report.js
Quite a few problems arising from configuration file errors that result in now test results, and then the internal `table` functions throwing. 
This PR conditions the passage of the "resultArray" to the `table` function and will log an error if no results are present.
=> Provide conditioning on input to table creation for report

packages/caliper-burrow/.gitignore, packages/caliper-burrow/.npmignore, packages/caliper-cli/.npmignore, packages/caliper-core/.npmignore, packages/caliper-ethereum/.npmignore, packages/caliper-fabric/.npmignore, packages/caliper-fisco-bcos/.npmignore, packages/caliper-generator/generator-caliper/.npmignore, packages/caliper-iroha/.npmignore, packages/caliper-sawtooth/.gitignore, packages/caliper-sawtooth/.npmignore
Currently during the Caliper publish phase, we are also publishing unrequired content such as:
- tests
- config files
This PR (should) stop that through the introduction of an npm ignore file
=> add npmignore file to packages

packages/caliper-cli/lib/lib/config.yaml
The registrarHelper.js present in the fabric v2 adaptor has a direct requirement on fabric-ca-client. This PR adds the required item to the bindings
=> Update the binding for v2

packages/caliper-cli/lib/lib/config.yaml
Turns out there was an official fabric-sdk-node release (who knew!) so we can now use that as an official binding.
Added new link for `latest-v2`
Would appear that there is no 2.0.0 version and just a 2.1.0 version, so we will have to skip the 2.0.0 entry
=> Update binding to official fabric-sdk-node

.travis/checks-and-unit-tests.sh, lerna.json, packages/caliper-generator/generator-caliper/.eslintignore, packages/caliper-generator/generator-caliper/.eslintrc.yml, packages/caliper-generator/generator-caliper/generators/app/index.js, packages/caliper-generator/generator-caliper/generators/benchmark/index.js, packages/caliper-generator/generator-caliper/package.json, packages/caliper-generator/generator-caliper/test/benchmark/callback.js, packages/caliper-generator/generator-caliper/test/benchmark/config.js, packages/caliper-publish/lib/version.js, packages/caliper-publish/lib/version/checkCommand.js, packages/caliper-publish/lib/version/fixCommand.js, packages/caliper-publish/lib/version/impl/check.js, packages/caliper-publish/lib/version/impl/fix.js
The PR adds package version check and fix functionality to the internal CLI. This check is also added to the CI test.
Covers and extends #758 
Bump the root json version, and run `./publish.js version check` from the `./packages/caliper-publish` directory. Note, that misaligned version in the packages themselves are picked up during lerna bootstrap.
Run `./publish.js version fix` from the `./packages/caliper-publish` directory after the previous bump. It should bump all package versions and cross-package dependencies to the root version.
=> Add package version check to internal CLI and CI test

packages/caliper-ethereum/lib/ethereum.js
Without this change, it's impossible to configure Ownable contracts and similar from within the benchmark callback script. This is useful for RBAC contracts as well.
=> ethereum: add contractDeployerAddress to context

packages/caliper-burrow/lib/burrow.js, packages/caliper-burrow/package.json, packages/caliper-cli/lib/lib/config.yaml
=> Improve burrow 0.30.2 support

packages/caliper-ethereum/lib/ethereum.js, packages/caliper-tests-integration/besu_tests/phase1/networkconfig.json, packages/caliper-tests-integration/besu_tests/phase2/networkconfig.json, packages/caliper-tests-integration/besu_tests/phase3/networkconfig.json, packages/caliper-tests-integration/ethereum_tests/config/docker-compose.yml, packages/caliper-tests-integration/ethereum_tests/networkconfig.json
Fixes #776. See https://github.com/hyperledger/caliper/issues/776#issuecomment-624771622 for more info.
Signed-off-by: Ben Burns <803016+benjamincburns@users.noreply.github.com>
=> ethereum: disallow http(s) RPC transports

_config.yml, _includes/v0.3.1.html, _includes/v0.3.html, _includes/vNext.html, _layouts/v0.3.1.html, docs.json, docs/v0.3.1/Architecture.md, docs/v0.3.1/BenchmarkConfiguration.md, docs/v0.3.1/Benchmark_Generator.md, docs/v0.3.1/Burrow_Configuration.md, docs/v0.3.1/CONTRIBUTING.md, docs/v0.3.1/Caliper_FAQ.md, docs/v0.3.1/Ethereum_Configuration.md, docs/v0.3.1/FISCO_BCOS_Configuration.md, docs/v0.3.1/Fabric_Configuration.md, docs/v0.3.1/Getting_Started.md, docs/v0.3.1/Installing_Caliper.md, docs/v0.3.1/Iroha_Configuration.md, docs/v0.3.1/LICENSE.md, docs/v0.3.1/Logging_Control.md, docs/v0.3.1/Messengers.md, docs/v0.3.1/MonitorsAndObservers.md, docs/v0.3.1/Rate_Controllers.md, docs/v0.3.1/Runtime_Configuration.md, docs/v0.3.1/Sawtooth_Configuration.md, docs/v0.3.1/Workload_Module.md, docs/v0.3.1/Writing_Adapters.md, docs/v0.3.1/Writing_Benchmarks.md, docs/v0.3.1/architecture_CH.md, scripts/bump-docs.js
New docs for 0.3.1
Also a fix for bumpdocs
- global replace to enable publish of x.y.z as well as x.y versions
- addition of trailing slash on html matcher to enable "contains" disambiguation for x.y and x.y.z
=> 0.3.1 release docs and bump fix for minor versions

_includes/header.html
This PR adds the useful "documentation" link back to the header bar, it uses the same logic as the main "getting started" button on the homepage so will not require editing the link every time a new release is produced.
**_Before_**
**_After_**
=> Adding docs link back to header so returning users can access docs easily

packages/caliper-fisco-bcos/lib/fiscoBcosApi.js, packages/caliper-fisco-bcos/package.json
This PR addresses the issue that a docker host is needed when using FISCO-BCOS adapter. 
Previously, as per the FISCO-BCOS adapter's implementation, a child process is spawned to invoke a `docker run`command for solidity contract compilation. This creates difficulty when running caliper against a remote network (e.g., with `caliper.command.start` and `caliper.command.end` removed and with the node endpoints set to a remote addresses in the network config). The environment (e.g., a container) that runs caliper may or may not have docker available and this requirement is not very necessary as the contract compilation is achievable through the js-based solidity compiler `solc-js`. 
(Someone may argue that [dind](http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) is …
=> Use solc-js library instead of docker to compile contracts in FISCO-BCOS adapter

CHANGELOG.md, lerna.json, package.json, packages/caliper-burrow/package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-iroha/package.json, packages/caliper-publish/package.json, packages/caliper-sawtooth/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
bump of version to 0.3.2 using `npm run version-fix` command
=> Update to stable Caliper release version 0.3.2

lerna.json, package.json, packages/caliper-burrow/package.json, packages/caliper-cli/package.json, packages/caliper-core/lib/common/config/Config.js, packages/caliper-core/lib/common/config/default.yaml, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/lib/adaptor-versions/v1/fabric-gateway-v1.js, packages/caliper-fabric/lib/adaptor-versions/v1/fabric-v1.js, packages/caliper-fabric/lib/adaptor-versions/v2/fabric-gateway-v2.js, packages/caliper-fabric/lib/adaptor-versions/v2/fabric-v2.js, packages/caliper-fabric/lib/fabric.js, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-iroha/package.json, packages/caliper-publish/package.json, packages/caliper-sawtooth/package.json, packages/caliper-tests-integration/fabric_tests/run.sh, packages/caliper-tests-integration/package.json, packages/generator-caliper/package.json
Taking full advantage of the semver change to make the fabric gateway config naming more sensible, whilst I was there I moved the network validation to a single location, rather than having it in each adaptor.
Docs PR to follow
=> 0.4.0 PR - modify fabric config file for gateway

docs/vNext/Fabric_Configuration.md, docs/vNext/Runtime_Configuration.md
=> 0.4.0 PR - Docs update to match Fabric gateway configuration changes

packages/caliper-core/lib/worker/rate-control/fixedBacklog.js, packages/caliper-core/test/worker/rate-control/fixedBacklog.js
Implementation based on suggestion from Hadera users: modify controller such that sleep time is derived from witnessed TPS and not latency. This is especially important when considering high TPS high latency systems
based on `deltaTXN * 1/TPS = sleep in seconds to build the desired txn load`
Current TPS is determined using `resultStats[1]` which is the batch TPS within the most recent txUpdate interval. This prevents use from using the global round statistics.
=> Modify backlog controller to use TPS to throttle

packages/caliper-core/lib/common/utils/caliper-utils.js
Now paths like `benchmarks/.../init.js` are also identified as local modules
=> Update local module path detection

README.md
Remove and replace the broken link in readme for installing and using Caliper. 
=> Change link in readme for installing and using Caliper

packages/caliper-core/lib/worker/rate-control/maxRate.js, packages/caliper-core/lib/worker/rate-control/rateControl.js, packages/caliper-core/test/worker/rate-control/fixedBacklog.js, packages/caliper-core/test/worker/rate-control/maxRate.js
Contributes to #870 
- Ramp the worker TPS conditionally between txUpdate phases, if a TPS drop (for an increased driving rate) is detected, back off and reduce the ramp
=> Add maximum-rate controller

packages/caliper-core/index.js, packages/caliper-core/lib/common/messaging/mqtt-worker.js, packages/caliper-core/lib/common/messaging/process-worker.js, packages/caliper-core/lib/master/orchestrators/worker-orchestrator.js, packages/caliper-core/lib/worker/caliper-worker.js, packages/caliper-core/lib/worker/message-handler.js
contributes to #871 
base on current naming convention in other folders, changed `caliper-local-client` to `caliper-worker` and removed unrequired folder nesting.
This now sits alongside `mqtt-worker`, `process-worker` quite neatly
=> change client -> worker in code

docs/vNext/Architecture.md, docs/vNext/BenchmarkConfiguration.md, docs/vNext/Installing_Caliper.md, docs/vNext/Runtime_Configuration.md, docs/vNext/Writing_Connectors.md
Update of vNext docs to modify `master` -> `manager`
Also updated version in `installing` to be 0.4.0
=> Update vNext docs for manager rename

packages/caliper-core/lib/worker/rate-control/fixedBacklog.js, packages/caliper-core/lib/worker/rate-control/fixedFeedbackRate.js, packages/caliper-core/test/worker/rate-control/fixedBacklog.js, packages/caliper-core/test/worker/rate-control/fixedFeedbackRate.js, packages/caliper-tests-integration/besu_tests/phase2/benchconfig.yaml, packages/caliper-tests-integration/besu_tests/phase3/benchconfig.yaml, packages/caliper-tests-integration/ethereum_tests/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase1/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase2/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase3/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase7/benchconfig.yaml, packages/caliper-tests-integration/iroha_tests/benchconfig.yaml
Rate controllers should be from the perspective of the SUT, with workers figuring out what loading they should supply.
This PR aligns the backlog controllers (fixed-backlog, fixed-feedback-rate) to this convention.
Question: Should `fixed-backlog` be renamed to something more appropriate, such as `fixed-transaction-load` or `fixed-load` ?
Docs change to accompany in #910 
=> Align backlog controllers with other rate controllers

packages/caliper-fabric/lib/configValidator.js, packages/caliper-fabric/lib/connector-versions/v1/fabric-gateway.js, packages/caliper-fabric/lib/connector-versions/v1/fabric.js, packages/caliper-fabric/lib/connector-versions/v2/fabric-gateway.js, packages/caliper-fabric/lib/connector-versions/v2/fabric.js, packages/caliper-fabric/lib/connector-versions/v2/registrarHelper.js, packages/caliper-fabric/lib/fabric-connector.js, packages/caliper-fabric/lib/fabricNetwork.js, packages/caliper-fabric/test/configValidator.js, packages/caliper-fabric/test/fabricNetwork.js
Contributes to #898 
Closes #882 
Specified clients can now pick from `organizationWallets` placed in the high level network configuration file
Fabric validator modified to check `organizationWallets` and condition subsequent entries
Fabric connectors now contains a map of organisation wallets, within which organisation identities are stored/used
Integration test runs 'gateway' mode for V1 and V2 SDK, supplementary manual test has been run using minimal network configuration and file based wallets targeting VSCode based network, for both V1 and V2 fabric networks/SDK.
=> move to organization based wallets for fabric connector

packages/caliper-fabric/lib/connector-versions/v1/fabric-gateway.js, packages/caliper-fabric/lib/connector-versions/v1/fabric.js, packages/caliper-fabric/lib/connector-versions/v2/fabric-gateway.js, packages/caliper-fabric/lib/connector-versions/v2/fabric.js, packages/caliper-tests-integration/fabric_tests/initByChannel.js, packages/caliper-tests-integration/fabric_tests/phase4/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase4/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase5/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase5/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase6/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase6/networkconfig.yaml, packages/caliper-tests-integration/fabric_tests/queryByChannel.js
Closes #898
PR changes within the Fabric connector:
adds the ability to specify channel name in the transaction arguments
modifies the gateway adaptors to enable selection of contracts in different channels
=> Enable transaction on named channels

.travis.yml, packages/caliper-burrow/lib/burrow-connector.js, packages/caliper-core/lib/common/core/blockchain-connector.js, packages/caliper-ethereum/lib/ethereum-connector.js, packages/caliper-fisco-bcos/lib/fiscoBcos-connector.js, packages/caliper-tests-integration/fisco-bcos_tests/get.js
- Remove legacy functions
- Disable Sawtooth and Iroha CI integration tests (it's time to let go of these connector refactors if we can't guarantee/test their correctness)
=> Remove legacy queryState function from the connector APIs

packages/caliper-burrow/lib/burrow-connector.js, packages/caliper-core/lib/common/core/blockchain-connector.js, packages/caliper-ethereum/lib/ethereum-connector.js, packages/caliper-fabric/lib/connector-versions/v1/fabric-gateway.js, packages/caliper-fabric/lib/connector-versions/v1/fabric.js, packages/caliper-fabric/lib/connector-versions/v2/fabric-gateway.js, packages/caliper-fabric/lib/fabric-connector.js, packages/caliper-fisco-bcos/lib/fiscoBcos-connector.js, packages/caliper-tests-integration/besu_tests/open.js, packages/caliper-tests-integration/besu_tests/query.js, packages/caliper-tests-integration/besu_tests/transfer.js, packages/caliper-tests-integration/ethereum_tests/open.js, packages/caliper-tests-integration/ethereum_tests/query.js, packages/caliper-tests-integration/ethereum_tests/transfer.js, packages/caliper-tests-integration/fabric_docker_distributed_tests/init.js, packages/caliper-tests-integration/fabric_docker_distributed_tests/query.js, packages/caliper-tests-integration/fabric_docker_local_tests/init.js, packages/caliper-tests-integration/fabric_docker_local_tests/query.js, packages/caliper-tests-integration/fabric_tests/init.js, packages/caliper-tests-integration/fabric_tests/initByChannel.js, packages/caliper-tests-integration/fabric_tests/query.js, packages/caliper-tests-integration/fabric_tests/queryByChannel.js, packages/caliper-tests-integration/fisco-bcos_tests/get.js, packages/caliper-tests-integration/fisco-bcos_tests/set.js, packages/generator-caliper/generators/benchmark/templates/workload.js, packages/generator-caliper/test/benchmark/workload.js
- Merge the parameters into a single object, or array of objects
- Use platform-neutral naming, e.g. request and read-only
- Extract common invoke/query code where possible
- Update CI workload modules
- Update generator template
Contributes to #888 
=> Simplify connector invoke/query API

packages/caliper-tests-integration/besu_tests/config/docker-compose.yml, packages/caliper-tests-integration/besu_tests/run.sh, packages/caliper-tests-integration/ethereum_tests/run.sh, packages/caliper-tests-integration/fabric_tests/run.sh, packages/caliper-tests-integration/fisco-bcos_tests/run.sh, packages/caliper-tests-integration/iroha_tests/run.sh, packages/caliper-tests-integration/sawtooth_tests/run.sh
Besu integration test was failing due to a missing volume mount
This PR fixes the docker compose file, and moves the test to fail at the same point as the ethereum tests, which is fixed with #979
Also adds a `docker ps -a` in the dispose stage which was the command used to discover the failed `docker-compose up` step
=> Besu integration test: Update docker-compose file

packages/caliper-core/lib/common/config/default.yaml, packages/caliper-core/lib/common/messages/prepareMessage.js, packages/caliper-core/lib/common/messages/testMessage.js, packages/caliper-core/lib/manager/orchestrators/worker-orchestrator.js, packages/caliper-core/lib/manager/test-observers/null-observer.js, packages/caliper-core/lib/manager/test-observers/observer-interface.js, packages/caliper-core/lib/manager/test-observers/test-observer.js, packages/caliper-core/lib/worker/caliper-worker.js, packages/caliper-core/lib/worker/rate-control/fixedFeedbackRate.js, packages/caliper-core/lib/worker/rate-control/fixedLoad.js, packages/caliper-core/lib/worker/rate-control/fixedRate.js, packages/caliper-core/lib/worker/rate-control/linearRate.js, packages/caliper-core/lib/worker/rate-control/maxRate.js, packages/caliper-core/test/worker/rate-control/fixedFeedbackRate.js, packages/caliper-core/test/worker/rate-control/fixedLoad.js, packages/caliper-core/test/worker/rate-control/fixedRate.js, packages/caliper-core/test/worker/rate-control/linearRate.js, packages/caliper-core/test/worker/rate-control/maxRate.js, packages/caliper-core/test/worker/rate-control/noRate.js, packages/caliper-ethereum/lib/ethereum-connector.js
While inspecting integration test logs noticed that the ethereum connector was throwing errors due to missing arguments. 
The offending line ended up being in the worker orchestrator, with an invalid index being used to specify workerArguments
Additional changes present in this PR from searching the error via removal of all "client" references
=> Ensure detection of contracts in benchmark from worker arguments

packages/caliper-fabric/lib/ConnectorConfiguration.js, packages/caliper-fabric/test/ConnectorConfiguration.js
Signed-off-by: RosieMurphy0 <rosie.murphy@ibm.com>
Adds a function that returns the array that holds the contracts for a specified channel from the config file. 
Contributes to #940
=> added getter for contract definitions

packages/caliper-core/lib/common/config/Config.js, packages/caliper-core/lib/common/config/default.yaml, packages/caliper-core/lib/common/utils/constants.js, packages/caliper-core/lib/manager/monitors/monitor-prometheus.js, packages/caliper-core/test/manager/monitors/monitor-prometheus.js, packages/caliper-tests-integration/fabric_tests/phase4/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase5/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase6/benchconfig.yaml
Contributes to #964 
- Adds basic auth
- changes to "include" option, that is regex based
- changes to array of query objects to run
Requires companion docs for breaking change
=> Modify prometheus monitor

packages/caliper-core/lib/worker/worker-message-handler.js
When benchmarking, the `__logHandling` method spams the console log somewhat, and distracts from the actual process.
This PR drops the level to `debug` which is more appropriate
=> Drop _logHandling log level

docs/vNext/MonitorsAndObservers.md
Prom monitor docs were still referring to v0.3.2 `exclude` block, where vNext has sensibly moved to an `include` list
=> Update Prom monitor docs

packages/caliper-core/lib/manager/monitors/monitor-docker.js, packages/caliper-core/lib/manager/monitors/monitor-process.js, packages/caliper-core/lib/manager/monitors/monitor-prometheus.js
Bug found while updating the caliper-benchmarks to add a travis build stage:
- with incorrectly specified monitor configuration files, or in cases of failure during `getStatistics`, the return object was incorrect and not able to be destructured into the required `{ resourceStats, chartStats }` shape as needed by the `report.buildRoundResourceStatistics()`; call
- This PR updates the monitor `getStatistics` methods to ensure compliance
=> Honour monitor getStatistics return requirement

packages/caliper-fabric/lib/identity-management/IdentityManager.js, packages/caliper-fabric/test/identity-management/IdentityManager.js
Identity manager was not waiting for the import call and also had the
parameters in the wrong order.
Also add support to allow for a non existent organization for the
getAliasName api.
=> Fix import call to wallet facade

packages/caliper-fabric/lib/connector-versions/v2/WalletFacade.js, packages/caliper-fabric/lib/connector-versions/v2/WalletFacadeFactory.js, packages/caliper-fabric/package.json, packages/caliper-fabric/test/connector-versions/v2/WalletFacade.js
This implements a wallet facade that wrappers node-sdk v2 wallets for the new fabric connector configuration
=> Add support for V2 Wallets

packages/caliper-cli/lib/lib/config.yaml
2.2.2 sdk has shown to have concurrency issues - remove this from the possible caliper bindings to prevent users from using known bad SDKs
=> remove ability to bind to broken fabric sdks

docs/vNext/Runtime_Configuration.md
A user can use basic auth to connect to prometheus server/push GW ... so lets help them
=> Add basic auth runtime settings to docs

packages/caliper-fabric/lib/connector-versions/v1/WalletFacade.js, packages/caliper-fabric/lib/connector-versions/v1/WalletFacadeFactory.js, packages/caliper-fabric/test/connector-versions/v1/WalletFacade.js
Signed-off-by: RosieMurphy0 <rosie.murphy@ibm.com>
Adds support for v1 connectors through 2 files: `WalletFacade` and `WalletFacadeFactory`. 
Contributes to #940
=> Added support for v1 connectors with wallets 

packages/caliper-tests-integration/besu_tests/caliper.yaml, packages/caliper-tests-integration/ethereum_tests/caliper.yaml, packages/caliper-tests-integration/fabric_tests/caliper.yaml, packages/caliper-tests-integration/fisco-bcos_tests/caliper.yaml, packages/caliper-tests-integration/generator_tests/fabric/caliper.yaml
Travis is not permitting access to create folders, so the ethereum tests are showing invalid errors. 
This PR modifies the ethereum/besu integration tests (report path)  to prevent the error
=> Prevent failures in integration tests

packages/caliper-cli/lib/lib/config.yaml, packages/caliper-ethereum/lib/ethereum-connector.js, packages/caliper-ethereum/package.json, packages/caliper-tests-integration/besu_tests/config/docker-compose.yml, packages/caliper-tests-integration/besu_tests/config/orion/key/orion.key, packages/caliper-tests-integration/besu_tests/config/orion/key/orion.pub, packages/caliper-tests-integration/besu_tests/config/orion/orion.conf, packages/caliper-tests-integration/besu_tests/package.json, packages/caliper-tests-integration/besu_tests/privatetxs/benchconfig.yaml, packages/caliper-tests-integration/besu_tests/privatetxs/networkconfig.json, packages/caliper-tests-integration/besu_tests/run.sh, packages/caliper-tests-integration/besu_tests/src/storage/storage.json, packages/caliper-tests-integration/besu_tests/src/storage/storage.sol, packages/caliper-tests-integration/besu_tests/store.js, packages/caliper-tests-integration/package.json
Besu supports [private transactions](https://besu.hyperledger.org/en/latest/Concepts/Privacy/Private-Transactions/) sent to a list of participant nodes. The library [web3js-eea](https://www.npmjs.com/package/web3-eea) supports sending private transactions to Besu.
By expanding the network configuration DSL and adding a few changes to the Ethereum connection, we can support sending private transactions to Besu using Caliper.
As a user, I want to have performance metrics of Besu when using private transactions.
N/A
N/A
The core of the fix was to update `ethereum-connector.js` to be able to send private transactions. The network config DSL was extended to support some Besu privacy configurations.
In the network configuration, the `ethereum` object now can have a `privacy` section, …
=> Added support for Besu private transactions

packages/caliper-fabric/lib/identity-management/IdentityManager.js, packages/caliper-fabric/test/connector-configuration/ConnectorConfiguration.js, packages/caliper-fabric/test/connector-configuration/ConnectorConfigurationFactory.js, packages/caliper-fabric/test/identity-management/IdentityManager.js
Implemented the _extractIdentitiesFromWallet method in the identity manager and the associated tests for the method. Takes identities from a wallet and stores them in the in memory wallet using an existing method. Changed some tests in the connector file as well that were effected. 
contributes to #940
=> Extract identities from wallet to memory wallet

package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/generator-caliper/package.json
Contributes to #965 
Bump node engines to v10.22, which matches:
- travis build engine
- caliper image published to docker hub
bump in npm to that matching the v10.22 build (6.14.0)
This PR has no impact on ability to bootstrap, or subsequent binding ... jumping above v10 will
=> update node engines to v10, matching travis and caliper image build

packages/caliper-fabric/lib/connector-versions/v1/FabricGateway.js, packages/caliper-fabric/lib/connector-versions/v1/FabricNonGateway.js, packages/caliper-fabric/lib/connector-versions/v2/FabricGateway.js, packages/caliper-fabric/test/connector-versions/v1/FabricNonGateway.js
Need to ensure we don't stop working when precaching the environment
because in a multiorg definition they may not have access to all the
channels defined.
This is an edge case because multiple org definitions is not a good use
of this implementation. But because it supports it we want to remove
this restriction.
=> support multiorg and channels

packages/caliper-fabric/lib/FabricConnectorFactory.js, packages/caliper-fabric/lib/connector-configuration/ConnectorConfiguration.js, packages/caliper-fabric/lib/connector-versions/v1/FabricNonGateway.js, packages/caliper-fabric/lib/identity-management/IdentityManager.js, packages/caliper-fabric/package.json, packages/caliper-fabric/test/FabricConnectorFactory.js, packages/caliper-fabric/test/connector-configuration/ConnectorConfiguration.js, packages/caliper-fabric/test/connector-versions/v1/FabricNonGateway.js, packages/caliper-fabric/test/identity-management/IdentityManager.js, packages/caliper-fabric/test/sample-configs/UnknownVersionConfig.yaml
=> Improve validation for new connectors

packages/caliper-tests-integration/fabric_docker_distributed_tests/mosquitto/mosquitto.conf, packages/caliper-tests-integration/fabric_tests/mosquitto/mosquitto.conf
Mosquitto v2 requires [explicit A&A settings](https://mosquitto.org/documentation/migrating-to-2-0/). 
This PR adds those settings to the CI tests, which **currently fail and block other PRs**.
=> Make Mosquitto authentication and authorization explicit for v2

docs/v0.3.2/Messengers.md, docs/v0.4.2/Messengers.md, docs/vNext/Messengers.md
Docs PR for #1128 
Added Mosquitto v2 info to every docs version mentioning MQTT.
=> Add Mosquitto v2 migration info for MQTT-based messengers

packages/caliper-cli/lib/lib/bindCommon.js
Signed-off-by: FranSoto7 <franciscomanuel.sotoramirez@gmail.com>
npx caliper bind command wouldn't work on a Windows machine, since the command for npm would be "npm.cmd" instead of just "npm".
Added a comprobation in runtime to check if the OS is Windows, otherwise it works like before.
=> FIX: caliper bind command now compatible with Windows OS

index.html
Signed-off-by: Aastha Bist <abist119@gmail.com>
- The link to Hyperledger Fabric configuration on [https://hyperledger.github.io/caliper/](https://hyperledger.github.io/caliper/) gives a 404 error on being clicked
The current documentation release v0.4.2 is the one being referenced so I kept the link for the new Fabric confic docs instead of the previous broken link.
=> Fixed link to Fabric connector configuration for docs v0.4.2 for Caliper website homepage

packages/caliper-core/lib/manager/monitors/monitor-docker.js
There is an issue that docker containers are only monitored during the first round of a multi-round benchmark as described in issue #1134.
The problem is caused by the fact that the `stop()` command sets the `this.containers` property to the empty array `[]`, while it expects a `null` value to (re)set the containers list. By setting this to `if (!this.containers || this.containers.length == 0)`, we account for both cases.
Resolves #1134
=> Resolve issue in which only first round would be docker-monitored

packages/caliper-tests-integration/generator_tests/fabric/run.sh, packages/generator-caliper/package.json
* Downgrade to v3 Yeoman generator in dependencies
* Downgrade to v3 Yeoman generator in integration test
Note: Yeoman v4 requires Node.js v14 LTS, bump back versions once Node version is also bumped.
=> Fix generator integration test

packages/caliper-core/lib/common/messages/testMessage.js, packages/caliper-core/lib/worker/rate-control/compositeRate.js, packages/caliper-tests-integration/fabric_tests/phase5/benchconfig.yaml
* Rename old "roundConfig" references to the new "testMessage"
* Extend TestMessage class with some functions to allow modification by CompositeRateController
* Fix passed arguments to the new RateControl constructor when creating subcontrollers
* Add a composite rate controller to one of the Fabric CI phases
Fixes #1181 
=> Fix CompositeRateController class bug (#1181)

packages/caliper-core/lib/manager/test-observers/default-observer.js
It uses milliseconds not seconds.
It shows like:
`caliper  | 2021.12.27-13:26:12.001 info  [caliper] [default-observer] 	Observer interval set to 5000 seconds`
Signed-off-by: Justin Yang <justin.yang@themedium.io>
=> Fix the unit of the interval of default-observer in the log

packages/caliper-cli/lib/lib/config.yaml
Issue in 1.4 node sdk means that some dependencies aren't available when
binding to a 1.4 fabric sut in the caliper docker container
closes #1146
=> address fabric:1.4 sut binding not working in caliper container

packages/caliper-core/lib/manager/monitors/monitor-docker.js, packages/caliper-core/test/manager/monitors/monitor-docker.js
fixes #1166 and #1159.
- adds normalization option for cpu usage metric of docker-monitor 
- fixes memory usage stat of docker-monitor
=> Docker monitor metrics fixes - cpu and memory usage

docs/vNext/MonitorsAndObservers.md
updated the vNext/MonitosAndObservers.md with documentation about new option to normalise the cpu usage metric of the Docker Monitor
=> new docker-monitor option to normalize cpuUsage

packages/caliper-core/lib/common/config/default.yaml, packages/caliper-fabric/lib/connector-versions/v1/FabricGateway.js, packages/caliper-fabric/lib/connector-versions/v1/FabricNonGateway.js, packages/caliper-fabric/lib/connector-versions/v1/fabric-gateway.js, packages/caliper-fabric/lib/connector-versions/v1/fabric.js, packages/caliper-fabric/lib/connector-versions/v2/FabricGateway.js, packages/caliper-fabric/lib/connector-versions/v2/fabric-gateway.js
This is the apparent cause of a caliper run hang where it continues to
run with unfinished txns. It's actually waiting 60,000 seconds for txns
to finish which won't finish as it looks like the node sdk misses the
events.
code part of #1141 also addresses in part
=> Correct timeout defaults

packages/caliper-cli/lib/lib/config.yaml
=> Update bindings to latest fabric sdks and remove old ones

docs/vNext/Fabric_Configuration_New.md, docs/vNext/Runtime_Configuration.md, docs/vNext/tutorials_fabric_existing.md
This is the documentation update to the PR that removes the need to
specify gateway-enabled for the fabric 2.2 SUT
=> update gateway-enabled references in docs

packages/caliper-core/lib/common/config/Config.js, packages/caliper-fabric/lib/connector-versions/v1/FabricGateway.js, packages/caliper-fabric/lib/connector-versions/v1/FabricNonGateway.js, packages/caliper-fabric/lib/connector-versions/v2/FabricGateway.js, packages/caliper-tests-integration/package.json
Also fixes
1. unused timeout property in fabric gateway connectors
2. ignore license check in generator tests for downloaded files
Doc update to follow
=> Remove CountQueryAsLoad Option

packages/caliper-fabric/lib/connector-configuration/ConnectionProfileDefinition.js, packages/caliper-fabric/lib/connector-versions/peer-gateway/PeerGateway.js, packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js, packages/caliper-fabric/test/connector-versions/peer-gateway/PeerGateway.js, packages/caliper-fabric/test/connector-versions/peer-gateway/PeerGatewayStubs.js, packages/caliper-fabric/test/sample-configs/Org2StaticConnectionProfile.yaml, packages/caliper-fabric/test/sample-configs/PeerGatewayNetworkConfigNotMutual.yaml
Added main logic for the new peer-gateaway connector with unit tests
=> Fabric Gateway connector implementation: PeerGateway.js implementation + unit tests

docs/v0.4.2/Fabric_Tut.html, docs/v0.4.2/tutorials_fabric_existing.md, docs/vNext/Fabric_Tut.html, docs/vNext/tutorials_fabric_existing.md
newer docker-compose versions don't work with the specific git checkout
in the tutorial.
I've fixed the bug in fabric-samples but as it hasn't been tagged as a
release yet we need to use another specific git commit but updates to
test-network now means it works with newer docker-compose versions.
closes #1291
=> address fabric tutorial not working with newer docker-compose

packages/caliper-core/lib/manager/report/report.js, packages/caliper-core/test/manager/report/report.js
=> remove latency values if no successful txns in final report

packages/caliper-cli/lib/bindCommand.js, packages/caliper-cli/lib/launch/launchManagerCommand.js, packages/caliper-cli/lib/launch/launchWorkerCommand.js, packages/caliper-cli/lib/unbindCommand.js
The documentation in vNext will also be updated in line with this
change.
=> Update the usage examples to more appropriate versions

packages/caliper-cli/lib/lib/config.yaml, packages/caliper-fabric/lib/FabricConnectorFactory.js, packages/caliper-fabric/test/FabricConnectorFactory.js, packages/caliper-fabric/test/connector-versions/peer-gateway/PeerGateway.js
- added logic to pick new Peer Gateway connector in the connector selector in FabriConnectorFactory.js 
- added 2.4 fabric SUT version with binding packages in .config.yaml
- added last fixes for the Peer Gateway connector implementation
=> Peer Gateway: Added Connector Selector implementation modifications to support the new Peer Gateway Connector

packages/caliper-core/lib/common/config/default.yaml, packages/caliper-fabric/lib/connector-versions/v1/FabricChannelOperations.js
edited defaul.yaml (updated comments and deleted sllep after option for fabric) + updated the fabric Chaincode operations for the v1 fabric connector
=> Fixes for default.yaml in packages/caliper-core/lib/common/config/ and updates for the fabric Channel operations for the v1 fabric connector

packages/caliper-tests-integration/fabric_tests/phase2/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase3/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase4/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase5/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase6/benchconfig.yaml, packages/caliper-tests-integration/fabric_tests/phase7/benchconfig.yaml
For the fabric tests the monitor intervals were set to single
millisecond values such as 3, 4, 5. This adds a massive overhead to the
running of the integration tests and isn't needed, so changing them to
be seconds instead.
=> Change monitor intervals from milliseconds to seconds

packages/caliper-core/lib/worker/caliper-worker.js, packages/caliper-core/test/worker/caliper-worker.js
This improves the cleanup of a worker if an error occurs which would
cause the worker to terminate the round.
closes #1312
=> address worker cleanup when an error occurs

packages/caliper-core/lib/manager/monitors/monitor-docker.js, packages/caliper-core/package.json, packages/caliper-core/test/manager/monitors/monitor-docker.js
- Eliminated the use of system information to retrieve local docker container metrics closes #1309 #1305 
- Upgraded the dockerode dependency and expanded it to be used for both local and remote containers stats monitoring
=> Fixed docker monitor to use Dockerode only

packages/caliper-core/lib/common/core/connector-base.js, packages/caliper-core/lib/worker/caliper-worker.js, packages/caliper-core/test/core/connector-base.js
A Scenario was discovered where if you send a single txn and the
connector throws an error then that single txn never finishes and the
worker loops forever waiting for that transaction to finish.
eg in the workload
```
invokerIdentity: 'unknownuser'
```
example benchmark
```
test:
name: fixed-asset-test
description: >-
This is a test yaml for the existing fixed-asset benchmarks
workers:
type: local
number: 1
rounds:
- label: empty-contract-evaluate
chaincodeID: fixed-asset
txNumber: 1
rateControl:
type: fixed-rate
opts:
tps: 2
workload:
module: benchmarks/api/fabric/workloads/empty-contract.js
arguments:
chaincodeID: fixed-asset
consensus: false
```
In the wider support for connectors though the caliper framework should
ensure that connectors that either don't handle errors or throw …
=> Ensure that connector errors finishes caliper transactions

packages/caliper-core/lib/common/config/default.yaml, packages/caliper-core/lib/worker/caliper-worker.js, packages/caliper-tests-integration/fabric_tests/phase3/src/marbles/node/package.json
To ensure that caliper manager and workers are at their most performant
out of the box, this disables logging debug output to a file
=> disable logging debug to file

packages/caliper-cli/lib/lib/config.yaml, packages/caliper-tests-integration/fabric_tests/phase3/src/marbles/node/package.json
Node SDK v1.4.20 relaxes the Node version check to >=10.13.0, so should be happy with any later Node version, even though only the LTS releases are “supported”
This upgrade will help remove all the warnings about node versions on caliper.
=> Upgraded node-sdk binding for fabric-v1-lts from 1.4.19 to 1.4.20

packages/caliper-cli/lib/lib/config.yaml
upgraded to new 2.2 node-sdk that specifies node 16
=> upgraded node-sdk binding for fabric-v2-lts from 2.2.11 to 2.2.12

docs/v0.4.2/tutorials_fabric_existing.md, docs/vNext/tutorials_fabric_existing.md
Replaced bit.ly with reference bootstrap.sh as per the build (but without the -k option)
=> Replaced bit.ly link with reference to bootstrap.sh

packages/caliper-cli/caliper.js, packages/caliper-cli/lib/launch/lib/launchManager.js, packages/caliper-cli/lib/launch/lib/launchWorker.js, packages/caliper-cli/lib/launchCommand.js, packages/caliper-cli/lib/lib/bindCommon.js
- Partially fixes #536 
- The error messages are clear and consistent.
- All the error messages are checked and updated.
=> Fix #536 Update error messages for 'caliper-cli' package

.github/workflows/main.yml
In this PR:
* Secrets are passed on from the parent workflow to the publish workflow as described in the GitHub Actions documentation
Fixes #1389
=> Pass secrets to CI workflow for publish

packages/caliper-tests-integration/generator_tests/fabric/run.sh
Signed-off-by: Tezas-6174 <jamdade.2@iitj.ac.in>
- Fixes #1377.
- Changed the generator binding from 2.2 to 1.4 in ``run.sh`` in generator-tests of ``caliper-test-integration`` package.
=> Fix#1377 Change the generator binding from 2.2 to 1.4

.github/workflows/dci.yml, .github/workflows/pr.yml, CHANGELOG.md, packages/caliper-core/test/worker/tx-observers/prometheus-push-tx-observer.js, packages/caliper-core/test/worker/tx-observers/prometheus-tx-observer.js, packages/caliper-tests-integration/fisco-bcos_tests/config/node0/config.ini, packages/caliper-tests-integration/fisco-bcos_tests/config/node1/config.ini, packages/caliper-tests-integration/fisco-bcos_tests/config/node2/config.ini, packages/caliper-tests-integration/fisco-bcos_tests/config/node3/config.ini
As recommended by the project update template and https://github.com/petermetz/gh-action-dci-lint
Let's see whether the remnant phrases in the changelog and third-party artifacts will trigger the alarm before making this a branch protection rule.
=> Add DCI linting to CI of PRs

packages/caliper-cli/lib/lib/config.yaml
- remove fabric-protos as not needed due to removal of fabric operations code
- update to latest 2.2 sdk which addresses discovery bug under load
=> update fabric bindings

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml, packages/caliper-cli/lib/lib/config.yaml, packages/caliper-tests-integration/besu_tests/run.sh, packages/caliper-tests-integration/ethereum_tests/run.sh, packages/caliper-tests-integration/fabric_tests/run.sh, packages/caliper-tests-integration/fisco-bcos_tests/run.sh, packages/caliper-tests-integration/generator_tests/fabric/run.sh, packages/caliper-tests-integration/run-tests.sh
In this PR:
* The integration tests workflow is refactored to be DRY
* The `node_modules` folder is cached across workflows
* The SUT binding is cached across integration test runs
Closes #1374
=> Cache node modules across CI workflows

.github/workflows/pr.yml
Reverts hyperledger/caliper#1423
This is because the changes were superseded by #1424
=> Revert "Add workflow for gh-pages branch"

.dcilintignore, .github/workflows/dci.yml, .github/workflows/pr.yml, docs/v0.5.0/Ethereum_Configuration.md, docs/v0.5.0/FISCO_BCOS_Configuration.md, docs/v0.5.0/Logging_Control.md, docs/vNext/Ethereum_Configuration.md, docs/vNext/FISCO_BCOS_Configuration.md, docs/vNext/Logging_Control.md
In this PR:
* GitHub actions workflows are added to the gh-pages branch
* Issues pointed out by DCI lint are fixed for the latest and vNext docs
This is done because according to [GitHub Docs](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow):
> The following steps occur to trigger a workflow run:
> ...
> 2. GitHub searches the .github/workflows directory in your repository for workflow files that are present **in the associated commit SHA or Git ref of the event**.
So, the workflow file is expected to be present in the gh-pages branch for it to run.
=> Add GitHub Actions workflow for docs

packages/caliper-core/lib/worker/tx-observers/prometheus-push-tx-observer.js, packages/caliper-core/test/worker/tx-observers/prometheus-push-tx-observer.js
In this PR:
* The worker index of each worker is added as a label when pushing metrics to PushGateway to distinguish workers.
Fixes #1354
=> Distinguish different workers in Prometheus PushGateway

.github/workflows/coverage.yml, .github/workflows/pr.yml, .github/workflows/unit-tests.yml, README.md, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-fisco-bcos/package.json, packages/caliper-gui-dashboard/package.json, packages/caliper-gui-server/package.json, packages/caliper-publish/package.json, packages/generator-caliper/package.json
In this PR:
* A step which reports coverage to Codecov is added to the unit tests workflow
Fixes #1278
=> Add coverage report workflow

.github/workflows/main.yml
In this PR:
* The coverage report workflow is run on merge as well so that the coverage of the main branch can be obtained and used as a basis for comparing the coverage of PRs.
=> Upload coverage reports on merge

packages/caliper-core/lib/worker/tx-observers/prometheus-push-tx-observer.js, packages/caliper-core/lib/worker/tx-observers/prometheus-tx-observer.js, packages/caliper-core/test/worker/tx-observers/prometheus-push-tx-observer.js, packages/caliper-core/test/worker/tx-observers/prometheus-tx-observer.js
* Fixed histogram calculation
* Fixed doc comment in test utility class
=> Fix calculation and doc comment in prometheus observer

.github/workflows/integration-tests.yml, .github/workflows/publish.yml, .github/workflows/unit-tests.yml
The fisco-bcos adapter and the generator don't seem to be compatible with node 18, hence the change is reverted until it is fixed.
=> Revert "Add Node 18 to CI (#1455)"

.github/workflows/integration-tests.yml
* Run integration tests when package-lock.json or the workflow file are modified
Fixes #1441
=> Fix integration test CI trigger

packages/caliper-core/lib/common/config/Config.js, packages/caliper-core/lib/common/config/default.yaml, packages/caliper-core/lib/common/messages/prometheusUpdateMessage.js, packages/caliper-core/lib/common/messages/workerMetricsMessage.js, packages/caliper-core/lib/worker/tx-observers/prometheus-manager-tx-observer.js, packages/caliper-core/test/worker/tx-observers/prometheus-manager-tx-observer.js
In this PR:
* The new TxObserver class is added (with tests) as a part of the ongoing effort to add a Prometheus scrape server to the Caliper manager.
PR 1/n for #1353
=> Add TxObserver for Prometheus manager

packages/caliper-core/.npmignore
In this PR:
* Workaround new npmignore rules from NPM 7 to include the missing `report.html`
Fixes #1451
=> Fix npmignore for report html

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
In this PR:
* The GitHub cache action is updated to v3
Fixes #1467
=> Update cache action

packages/caliper-core/lib/manager/monitors/monitor-docker.js
#1493 
1. Add target remote docker container to monitoring in test config
2. Run Caliper targeting the remote docker
[How do I measure the performance of remote docker container in hyperledger caliper?](https://stackoverflow.com/questions/75764196/how-do-i-measure-the-performance-of-remote-docker-container-in-hyperledger-calip)
Removed .remote in line 75 of monitor-docker.js, was likely a typo that was just missed since filterName has no property named remote
Ran a remote monitoring with good results
[report.zip](https://github.com/hyperledger/caliper/files/11498024/report.zip)
=> docker monitor remote monitoring bugfix

.github/workflows/publish.yml
This is more of a case of quickly dropping down to an older version of `npm` so that it will fix the publish action.
Ideally we want to move to a supported version of node and address the issue that comes with that version of npm to perform a publish. It could be
1. move to an older version of npm (ie that one that comes with node 16), but this is not ideal
2. move to a newer version of npm as it may be an issue with the version that came with node 18, but this isn't likely
3. look at the npm publish command to see what needs to be done to make it work.
=> Temporarily revert publish to using node 16.x to fix broken publish

.build/publish-caliper.sh, .github/workflows/publish.yml
downgrade the version of npm on the publish step to ensure that publish doesn't give an ENOWORKSPACES error
This should be considered a temporary solution to getting publish working again and a better solution needs to be found.
=> downgrade npm on publish as temp fix

Gemfile
Link to the issue: #1525 
1. Navigate to the documentation section.
2. Attempt to run the documentation locally using the previous configuration.
3. Observe the error related to loading 'rexml/parsers/baseparser' file.
The fix involved updating the Gemfile to use newer versions of dependencies, specifically targeting the issue related to loading 'rexml/parsers/baseparser' file. This approach was chosen to address the root cause of the error and ensure compatibility with the latest dependencies.
After implementing the fix, I tested it locally by running the documentation server. The error related to loading 'rexml/parsers/baseparser' file no longer occurred, confirming that the fix resolves the issue.
Automated tests were not applicable for this fix.
Documentation update is pending.
=> Resolve issue with documentation rendering locally #1525

package-lock.json, packages/caliper-core/lib/worker/tx-observers/prometheus-push-tx-observer.js, packages/caliper-core/lib/worker/tx-observers/prometheus-tx-observer.js, packages/caliper-core/package.json
reasons for this
1. we have never documented the metrics
2. not sure how much use it is anyway
3. was using an old version of gc-stats which is now unmaintained and has security issues
4. replacement version of gc-stats is maintained by a single person who controls the binary builds available so is a dangerous thing to rely on
5. it has no pure javascript fallback therefore requires caliper to pull down or build a binary module (meaning you need python and compilers installed) which will also be dependent on the version of node being used.
=> Remove collection of node gc stats in prometheus

docs/vNext/CONTRIBUTING.md, docs/vNext/Caliper_FAQ.md, docs/vNext/Fabric_Configuration_New.md, docs/vNext/Getting_Started.md, docs/vNext/Installing_Caliper.md, docs/vNext/tutorials_fabric_existing.md
- prepare vNext to represent a 0.5.1 release
- move all references of fabric to now demonstrate the `fabric-gateway`
=> Update docs around fabric-gateway and 0.5.1 release

packages/caliper-core/test/common/core/messages/assignedMessage.js, packages/caliper-core/test/common/core/messages/message.js, packages/caliper-core/test/common/core/messages/preparedMessage.js, packages/caliper-core/test/common/core/messages/readyMessage.js
This PR introduces the tests for the base `Message` class in `caliper-core`, and then introduces three similar test suites for the constructors of three types of messages. When approved, I can work on adding similar tests for all the message classes. 
Fixes part of #1557 
1.
2.
3.
4.
=> `caliper-core`: add tests for `Message` classes

packages/caliper-core/test/common/core/messages/message.js
The original test assumes that the 2 generated dates will occur on the exact same millisecond which is going to be unlikely. This fix allows for upto a 5 second discrepancy
=> Address test flake due to timing

docs/v0.6.0/Ethereum_Configuration.md, docs/vNext/Ethereum_Configuration.md
Caliper Ethereum documentation was outdated and did not provide information on using the `--caliper-flow-skip-install`  that skips the smart contract installation phase.
Issue #1589 - Caliper ethereum documentation needs a complete overhaul
* Added information on how to use the `--caliper-flow-skip-install` to use pre-deployed contracts. Since the contract configuration on the network config file will differ depending on whether this flag is used, I added a subsection for each use case;
* Added a warning regarding the mandatory usage of `fromAddressSeed` when using more than 1 worker;
* Fixed name mismatches between the network config file keys;
* Added information about the TxStatus type - `getResut()` was not documented;
* Updated references to the old `invokeSmartContract` and …
=> Caliper Ethereum documentation overhaul

packages/caliper-core/test/worker/tx-observers/prometheus-tx-observer.js
1.
2.
3.
4.
- caliper-core/lib/worker/tx-observers/prometheus-tx-observer.js : 92.06
- caliper-core/lib/worker/tx-observers/prometheus-tx-observer.js : 77.77
=> add test for more tests for prometheus transaction observer

CONTRIBUTING.md, docs/source/connectors/fabric-config.md, packages/caliper-cli/lib/lib/config.yaml, packages/caliper-tests-integration/fabric_tests/run.sh
- add binding `gateway` (to replace `fabric-gateway`) and make this the default in the docs
- change the integration tests to bind to gateway instead of 2.4
=> Fix contributing.md

packages/caliper-core/test/worker/worker-message-handler.js
1.
2.
3.
4.
- caliper-core/lib/worker/worker-message-handler.js: 89.13
- caliper-core/lib/worker/worker-message-handler.js: 9.78
=> add test for the message handling behavior

packages/caliper-core/lib/worker/caliper-worker.js, packages/caliper-core/test/worker/caliper-worker.js
1.
2.
3.
4.
- caliper-core/lib/worker/worker-message-handler.js: 89.13
- caliper-core/lib/worker/worker-message-handler.js: 9.78
=> Add more tests for caliper worker

packages/caliper-core/lib/worker/tx-observers/logging-tx-observer.js, packages/caliper-core/lib/worker/tx-observers/tx-observer-dispatch.js, packages/caliper-core/test/worker/tx-observers/logging-tx-observer.js, packages/caliper-core/test/worker/tx-observers/tx-observer-dispatch.js
1.
2.
3.
4.
- caliper-core/lib/worker/tx-observers/logging-tx-observer.js: 100
- caliper-core/lib/worker/tx-observers/logging-tx-observer.js: 0
=> add test for test-logging-tx-observer

packages/caliper-core/test/manager/caliper-engine.js
=> add test for caliper-engine module

packages/caliper-core/lib/worker/rate-control/fixedFeedbackRate.js, packages/caliper-core/test/worker/rate-control/fixedFeedbackRate.js
1.
2.
3.
4.
- caliper-core/lib/worker/fixedFeedbackRate.js: 80
- caliper-core/lib/worker/fixedFeedbackRate.js: 60
=> add more test for fixedFeedbackRate controller implementation

CHANGELOG.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, README.md, docs/mkdocs.yml, docs/source/concepts/caliper-messengers.md, docs/source/concepts/logging-control.md, docs/source/concepts/runtime-config.md, docs/source/concepts/workload-module.md, docs/source/connectors/ethereum-config.md, docs/source/connectors/fabric-config.md, docs/source/connectors/writing-connectors.md, docs/source/getting-started/contributing.md, docs/source/getting-started/faq.md, docs/source/getting-started/installing-caliper.md, docs/source/index.md, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-ethereum/lib/ethereum-connector.js, packages/caliper-ethereum/package.json, packages/caliper-fabric/package.json, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json, packages/generator-caliper/.yo-rc.json, packages/generator-caliper/package.json
=> feat: updated github links

packages/caliper-core/lib/worker/rate-control/recordRate.js, packages/caliper-core/test/worker/rate-control/recordRate.js
1.
2.
3.
4.
- caliper-core/lib/worker/recordRate.js: 95.52
- caliper-core/lib/worker/recordRate.js: 43.28
=> add more test for recordRate rate-controller

docs/source/concepts/rate-controllers.md
=> fix: record rate doc section

docs/source/getting-started/faq.md
=> fix: throughput faq

docs/source/concepts/caliper-messengers.md, docs/source/concepts/logging-control.md, docs/source/concepts/rate-controllers.md, docs/source/connectors/ethereum-config.md, docs/source/connectors/fabric-config.md
Small PR - Commit 0f936eacdd4fa30049dae424bfdcb4b74e36694a refactored core structure and mirror test folders to match new abstraction layout. This PR adjusts sources to changes.
=> Fix refactored core structure references

CONTRIBUTING.md, docs/source/getting-started/installing-caliper.md, docs/source/tutorial/fabric.md
Added link to hyperledger-caliper doc, and some additional link documentation
=> corrected the caliper documentation link

.build/publish-caliper.sh
Fixes #1707 
I opted for an easier solution since we only need this file when publishing
=> Add npm-shrinkwrap.json file and distribute it during publishing

package-lock.json, packages/caliper-publish/artifacts/npm-publish.sh, packages/caliper-publish/lib/npmCommand.js, packages/caliper-publish/publish.js
=> fix: Remove NPM token check from publishing script (#1712)

.github/workflows/integration-tests.yml, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-fabric/package.json, packages/caliper-publish/artifacts/npm-publish.sh, packages/caliper-publish/lib/impl/npm.js, packages/generator-caliper/package.json
Fixes #1714 
* tell the npm config command explicitly that it does not operate with workspaces
* set root package to private to prevent accidental publishing of monorepo
* updated git repo naming format in package.json files
=> fix: NPM publishing with workspaces (#1714)

.build/publish-caliper.sh, docs/source/concepts/logging-control.md, docs/source/connectors/fabric-config.md, docs/source/connectors/writing-connectors.md, docs/source/getting-started/installing-caliper.md, docs/source/index.md, docs/source/tutorial/fabric.md, package-lock.json, package.json, packages/caliper-cli/package.json, packages/caliper-core/package.json, packages/caliper-fabric/package.json, packages/caliper-publish/caliper.Dockerfile, packages/caliper-publish/package.json, packages/caliper-tests-integration/package.json
Caliper 0.7.0 is very broken, as we don't have any tests that test either the npm packages or the Docker image before they get published we have no way to detect this (luckily someone was trying to use the latest release)
We need to publish a complete new version (0.7.1) and ditch the 0.7.0 docs completely
=> Caliper 0.7.0 is very broken
